### ISSUE TITLE
Private Accounts

### ISSUE THREAD

**Issue by jeyemwey** [Traewelling/traewelling#1]
**Is your feature request related to a problem? Please describe.**

I want to track my public transport journeys, but I don't want to share them.

**Describe the solution you'd like**

- [x] New followers need to be accepted (see Twitter's protected accounts). 
- [x] Only those can see my check-ins and everything on my profile page.
~- [ ] I can mark some of my check-ins as unlisted (next to the "tweet" / "toot" checkboxes)~ (Moved to #305)
- [x] My private check-ins don't appear on maps ("en route" or event pages)
~- [ ] I can change the visibility of a check-in afterwards.~ (Moved to #305)

**Describe alternatives you've considered**

Marking a user account and all of its check-ins as insivible is a good first step.

**Additional Context**

[Related Gitlab issue](https://gitlab.com/HerrLevin_/trwl/issues/2)

**Comment by HerrLevin** [comment]
Fixed with #299
