### ISSUE TITLE
0km bus ride because saarVV is weird

### ISSUE THREAD

**Issue by jeyemwey** [Traewelling/traewelling#10]
**Describe the bug**
https://traewelling.de/status/118639 is a 0km bus ride, because the RMV is doing weird things with Hafas.

**To Reproduce**
1. Search for `Homburg Hbf`
2. Select an R7 bus to `ZOB (Stadtmitte), Zweibrücken`
3. Check-in until `ZOB (Stadtmitte), Zweibrücken`.
4. Check the logged distance 

**Expected behavior**
The distance is correct (~ 13km).

**Screenshots**
![grafik](https://user-images.githubusercontent.com/2796271/74873410-7188a300-535f-11ea-9321-abd6d8ace423.png)

**Additional context**

RMV seems to squeeze two busses (one-way and back) into a single hafas trip (see attached screenshot from the API). While this does not _explain_ the error on this particular journey, it certainly contributes to its weirdness.

**Comment by aledjones** [comment]
Uhm.. thats not RMV. It's saarVV.

**Comment by jeyemwey** [comment]
Can you check wether the issue still persists?

**Comment by aledjones** [comment]
It does. Checked yesterday.

**Comment by HerrLevin** [comment]
Is this closed with #210? (@MrKrisKrisu)

**Comment by MrKrisKrisu** [comment]
#210 doesn't change the distance calculation. 
-> So no, this should still occur.

**Comment by aledjones** [comment]
It recently occurred again 

[https://traewelling.de/status/157824](https://traewelling.de/status/157824)
