### ISSUE TITLE
Delay Statistics

### ISSUE THREAD

**Issue by Omit6000** [Traewelling/traewelling#1005]
List and add up delays in transport and display them as statistics.  So that you can see how much delay you have accumulated in a certain time interval.

**Comment by MrKrisKrisu** [comment]
It should be noted that a delay occurring during the journey is not currently saved. Only the delay data at the time of check-in is stored.
Therefore, such statistics would not (**currently**) make sense.

**Comment by Omit6000** [comment]
Hey, maybe you can do a synchronisation with "Travelynx" for delays.
Travelynx saves this data.
Greetings, Timo

Kris ***@***.***> schrieb am So., 14. Aug. 2022, 17:52:

**Comment by MrKrisKrisu** [comment]
We also save the delay. However, we do not currently update it **during the trip** because the associated script has been disabled.

see #1015

**Comment by ChristianTacke** [comment]
What about updating the delays if a user modifies the status?
