### ISSUE TITLE
Check-in not possible when arrival time not set

### ISSUE THREAD

**Issue by fzakfeld** [Traewelling/traewelling#1010]
**Describe the bug**
Some trains have stops which don't have an arrival time because they are not meant for getting off. However, you "can" still get off there. Currently traewelling shows the error "arrival muss ausgefüllt werden." when doing this. An example is shown below.

**To Reproduce**
Check in to ICE 1689 on 2022-08-14, From Hamburg Hbf (departs at 22:12) to Hamburg-Harburg. Harburg won't have an arrival time set.

**Expected behavior**
I think it should be possible to check in anyways because you "can" use this train to get from Hamburg Hbf to Harburg (I certainly did). If the arrival is blank it could simply be the same as the departure and vice-versa.

**Screenshots**
<img width="901" alt="image" src="https://user-images.githubusercontent.com/43890789/184714011-b218f713-42e5-45db-9ccc-6b5e169d7165.png">

**Comment by jheubuch** [comment]
As you said, those trains are not meant to be left at those "only departure" stations. Furthermore it isn't a common use case (except goodwill-offers in case of disruptions) for leaving the train on those "only departure" stations.

Sure, you "can" get out of the train there, but this is not provided by Deutsche Bahn in those certain situations, so I think you also should not be able to check into those trains.

**Comment by fzakfeld** [comment]
I don’t really see a reason why you shouldn’t be able to check in to those trains. In Hamburg they are actively encouraging passengers to take the IC/ICE options as a replacement for the S-Bahn lines S3 and S31.

Isn’t Traewelling all about documenting *all* of your public transport journeys?

**Comment by marc-maurer** [comment]
> Sure, you "can" get out of the train there, but this is not provided by Deutsche Bahn in those certain situations, so I think you also should not be able to check into those trains.

IMHO this feature should be included to improve the user experience.

Blaming this on a missing field in the DB API response is an excuse to do nothing.
Then please say openly that the technical effort is not worth it to you.

@fzakfeld Has given a useful use case as an example here.

**Comment by Fabian-C** [comment]
I can somewhat agree, in Hamburg and also Berlin I always prefere the ICEs and ICs for fast movement around the city.
For example, there ist only a 20 Minuten reaccouring RE connection between Berlin Hauptbahnhof und Berlin Südkreuz that can be taken without the need to change at another station. Often you see some users check-in in to other trains with a note that they actually took another ICE train.
I use those especially when traveling with other BahnCard or Netzcard owners or on my own. This is also a popular choice when traveling with the ICE 920 to Hamburg Altona. After arrival you can choose one of 3 Ice Trains within 10 minutes of each other going back to Hamburg HBF arriving at 07:25 / 07:35 ..... Where the DB Lounge then opens at 7:30.
