### ISSUE TITLE
DB-Lounge - Checkin

### ISSUE THREAD

**Issue by GrafPanto** [Traewelling/traewelling#1036]
Checkin - Funktion für DB-Lounged Analog zu Zug-Checkins. Mit Anzeige der Personen, die ebenfalls da sind

**Comment by jeyemwey** [comment]
Finde die Idee gut. Um das Dashboard (also die Träwelling-Hauptseite) nicht unnötig aufzublähen, würde ich das jedoch in ein eigenes Interface stecken, also eine Unterseite mit den bestehenden Checkins und Eincheckmöglichkeit.

Die Menge an DB Lounges [ist stark beschränkt](https://www.bahn.de/service/zug/db_lounge), sodass wir eine manuelle Liste pflegen/updaten könnten. Dann muss das nur noch jemand bauen :D

**Comment by MrKrisKrisu** [comment]
I have created a table for locations and management tools in the admin panel in #1037.

**Comment by marhei** [comment]
> Die Menge an DB Lounges [ist stark beschränkt](https://www.bahn.de/service/zug/db_lounge), sodass wir eine manuelle Liste pflegen/updaten könnten. Dann muss das nur noch jemand bauen :D

Wenn man so ein Feature schon einbaut sollte man gerade im Hinblick auf zunehmende Nutzung im Ausland (Coucou la France !) vielleicht nicht nur DB Lounges aufnehmen…

**Comment by f2k1de** [comment]
https://www.railteam.eu/de/fur-ihre-reise/railteam-serviceleistungen/lounges/

**Comment by MrKrisKrisu** [comment]
Es gab in letzter Zeit verschiedene Meinungen, ob der Checkin von statischen Locations bei Träwelling eingebaut werden sollte. Ich persönlich würde wahrscheinlich auch eher davon absehen und dafür eher auf Plattformen wie [Swarm](https://de.swarmapp.com/) verweisen, sodass wir uns eher auf "bewegte Objekte" fokussieren.

**Comment by Oxbowatos** [comment]
Ich habe in letzter Zeit öfters gesehen wie leute in Checkins schreiben das diese zu den DB Lounges gehen.
So wie ich das verstehe würde da eine Option zum einchecken in die DB Lounge besser sein als die Checkins von Zügen, Bussen, Trams, etc mit dem Text zu beschreiben.

Es würde auch ermöglichen zu sehen wer alles gerade in der DB Lounge ist.
Man muss ja auch keine Punkte dafür erhalten es reicht ja wenn man Punkte für "Bewegte Objekte" erhält

**Comment by HerrLevin** [comment]
Ich bin leider ebenso auf der Seite von @MrKrisKrisu und würde Swarm als einen Checkin-Dienst für statische Objekte empfehlen, da es dann doch weitere Komplexität mit in das Projekt gibt und die UI jetzt schon nicht die übersichtlichste ist. Dementsprechend würde ich das Ticket jetzt schließen.
