### ISSUE TITLE
🎆 Träwelling Year in Review

### ISSUE THREAD

**Issue by jeyemwey** [Traewelling/traewelling#1060]
Inspiriert von [diesem Tweet](https://twitter.com/I_Siebert/status/1573662692900052994): Wie könnte ein Träwelling Year in Review aussehen?

<img width="274" alt="image" src="https://user-images.githubusercontent.com/2796271/192102477-00678914-6ad8-4103-a8d1-6997aa63329b.png">

Ich stelle mir verschiedene Punkte vor, die angezeigt werden könnten (Liste nicht abschließend, hier nur Vorschläge, weißt eh):

* Aggregations:
  * [x] Summe Kilometer (sum)
  * [x] Summe gefahrene Zeit (sum)
  * [x] Summe Ankunftsverspätung
  * [ ] Anzahl verschiedener Modes of Transport
  * [x] Anzahl verschiedener EVUs (sumByHafasOperator)
  * [x] Anzahl verschiedener Linien per EVU (sumByHafasOperatorAndLine)
  * [ ] Anzahl verschiedener Länder (wenn man das herausfinden kann?)
  * [ ] Anzahl Check-ins mit anderen Träwellern
  * [x] Top Mit-Träweller (getTopTravellingWith)
  * [ ] Anzahl Check-ins mit Events
* Persönliche Sortings:
  * [x] Längste Fahrt (nach km und nach Zeit) --> Nur unterschiedlich anzeigen, wenn das zwei verschiedene sind (getLongestTrips)
  * [x] Fahrt mit höchster/geringster Geschwindigkeit (getTripsBySpeed)
  * [x] Fahrt mit meister Ankunftsverspätung (getTripsByArrivalDelay)
  * [ ] Tag mit meisten Checkins / meisten Kilometern / längster Zeit
  * [ ] Größtes / Kleinstes teilgenommenes Event (nach Anzahl Check-ins)
* Herausstehendes:
  * [ ] "An dieser Station war niemand so oft wie du"
  * [x] "Du bist die einzige mit Check-in an dieser Station" (getLonelyStations)
  * [ ] "Niemand hat so viele Check-ins in $Land wie du"
  * [ ] "Niemand ist so oft mit $EVU gefahren wie du"

Technisch gesehen habe ich keine Idee, wie man das umsetzt:
* In Trwl / Laravel oder als eigene Webseite/Service? Vielleicht eigene Webseite/React-App, die über Trwl ausgeliefert wird und so Zugang zum Backend erhält?
* Daten live beim Request erheben oder einmal nachts in einer ruhigen Minute die Datenbank abschießen und dann cachen? (Maybe über [Laravel Cache](https://laravel.com/docs/9.x/cache) oder über rausgerenderte HTML-Seiten?)
* usw usw

**Mich interessiert mal, was ihr dazu sagt** :)

**Comment by HerrLevin** [comment]
Wir könnten uns evtl. An https://github.com/remotion-dev/github-unwrapped / https://www.githubunwrapped.com orientieren.

**Comment by MrKrisKrisu** [comment]
In #1197 arbeite ich gerade die ersten Statistiken ein und habe bereits einen API Endpoint gebaut, der eine JSON Response mit den Stats ausgibt. Der Endpoint ist mit einem zusätzlichen Token abgesichert, damit erstmal nur unser eigenes Frontend drauf zugreifen kann.

@HerrLevin versucht ein Frontend dafür zu bauen in einem extra Repo.

Ich denke da kann man sich dann am besten via OAuth einmal einloggen und sieht sein vorbereitetes Review.

**Comment by jeyemwey** [comment]
Bitte Hotzo-Toot in eventuellen Blogpost einbauen, ja? https://mastodon.social/@elhotzo/109433066916250225

**Comment by MrKrisKrisu** [comment]
Backend ist im develop.
JSON ist über die normale User-Auth erreichbar unter `http://localhost:8000/year-in-review`
