### ISSUE TITLE
Missing character count 

### ISSUE THREAD

**Issue by Fabian-C** [Traewelling/traewelling#1064]
**Describe the bug**

Missing character counter while editing the check-in descriptions.
The new counter for available characters left to use is not Displayed. 
The counter ist only available at the initial check-in.
Why should this get changed: 
Some Informations that may be interesting to note down can be entered to the freetext body. An Example:  (the reason for a delayed arrival) there it would be interesting to get a feedback of te available characters left. 

**To Reproduce**

1. Go to 'a journy of your own'
2. Click on 'the "editing" menu'
4. See error 'notice the Missing counter under the textbox'

**Screenshots**

![Screenshot_20220925-225250](https://user-images.githubusercontent.com/41996761/192165193-5f8c9a9a-f92d-4e2c-86be-cb0568c232f6.png)

**Smartphone (please complete the following information):**

- Device: [Moto G7 Plus]
- OS: [Android 10]
- Browser [ Edge, Firefox Focus (Firefox Klar)]

**Additional context**
 None

**Comment by MrKrisKrisu** [comment]
Oh, thank you! I will fix this tomorrow.
