### ISSUE TITLE
Filters redirecting to wrong stations

### ISSUE THREAD

**Issue by sinsa92** [Traewelling/traewelling#1082]
**Describe the bug**
I am an active user of the "Last stops" feature where I can easily get the station I'm at for my next check-in. Since Bern is my main travelhub, I often change connections there.
Now, when I arrive with certain conection, I arrive at "Bern Hauptbahnhof" instead of "Bern". If I now select my last stop (Bern Hauptbahnhof) and try to filter for e.g. only express trains, it returns me all express train departures for "Bernburg Hbf". That effectively means i always have to re-type the Station name (Bern) and then the filter works normally.

**To Reproduce**

1. Search for "Bern, Mittelstrasse"
2. Check in on any bus of the lines 102-107 going to Bern, Hauptbahnhof until the terminus
3. Click on the most recent station in your history (which should be Bern, Hauptbahnhof)
4. Use the filter to show only S-trains departures
5. S-trains departures for Bernburg Hbf appear

**Expected behavior**
After step 4, I expect S-trains departures for Bern to appear

The Bug happens on both my smartphone and my laptop:
**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox Developer Edition
- Version: 106.0b5

**Smartphone (please complete the following information):**

- Device: iPhone 8+
- OS: iOs 15.7
- Browser: Safari
- Version: 15.7

**Comment by sinsa92** [comment]
I've found another case with the same issue: "Lausanne, gare" redirecting to "Lausanne, Beauregard" (Can be tested by checking into Bus lines 3, 20, 21 from "Lausanne, Pont Chauderon" in the direction of "Lausanne, gare" or "Paudex, Verrière", or alternatively by checking into Métro line m2 from "Lausanne-Flon" in the direction of "Ouchy-Olympique").

**Comment by MrKrisKrisu** [comment]
When the station board is open and a filter is clicked, we re-search the station at HAFAS. HAFAS then unfortunately returns the wrong station. We have already switched to the ID in most places, but at this point we still use the station name.
