### ISSUE TITLE
CSV export broken

### ISSUE THREAD

**Issue by jheubuch** [Traewelling/traewelling#1083]
**Describe the bug**
When I want to export my data as a CSV from 01.06.2018 to 31.10.2022, I only get the data until 20.03.2022 (Check-In #301725).
The check-ins after that are missing

**To Reproduce**

I think you can't reproduce as long you haven't got my credentials.

**Expected behavior**
I expect a full export of my data.

**Comment by MrKrisKrisu** [comment]
I can't reproduce this. I also get older data. Also tested with your account.

**Comment by MrKrisKrisu** [comment]
@jheubuch showed me his export, the problem occurs. I still cannot reproduce it.
Maybe check if it duplicates with #1112.

**Comment by jheubuch** [comment]
already fixed. Thanks
