### ISSUE TITLE
En Route map doesn't show journeys from/to FF

### ISSUE THREAD

**Issue by jeyemwey** [Traewelling/traewelling#11]
**Describe the bug**
The en route map sometimes doesn't show journeys from/to Frankfurt(Main) Hbf and/or they're longer than 1h. I don't know why, and I don't know how, but that seems to be the only connection between all journeys that are hidden.

**To Reproduce**
1. Check into any train from/to ds100:FF.
2. Open the "en route" page.

**Expected behavior**
The polyline is displayed

**Screenshots**
![grafik](https://user-images.githubusercontent.com/2796271/74874894-b6153e00-5361-11ea-9569-e27e59c618b5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 73

**Additional context**
The issue sometimes happens on other journeys, too - so I guess it's another flaw.

[Related Gitlab issue](https://gitlab.com/HerrLevin_/trwl/issues/171)

**Comment by MrKrisKrisu** [comment]
Cannot reproduce anymore. Please reopen if this still exists.

![image](https://user-images.githubusercontent.com/4103693/107889762-0d1e0680-6f15-11eb-9d50-2c6b3316a84e.png)
