### ISSUE TITLE
PDF and JSON export broken

### ISSUE THREAD

**Issue by Trexmex** [Traewelling/traewelling#1112]
**Describe the bug**
When I want to export my data as a .JSON or .PDF from 04/2020 to 10/2022, I am getting shown a 500 server error. 

**To Reproduce**

1. Go to 'export data' page
2. Click on 'export as .pdf/.json'
3. See error

**Expected behavior**
Download of the export file in .pdf or.json.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox, Chrome
- Latest version

**Smartphone (please complete the following information):**

- Device: Iphone 8
- OS: iOS16
- Browser: safari
- Latest Version

**Additional context**
Export as .csv is incomplete (ID335915 and above: 04/2022 until 10/2022)

**Comment by jeyemwey** [comment]
Hil Ich habe gerade mal auf dem Server nachgeschaut, es scheint sich um einen "Randfall" zu handeln, wenn man Checkins für 26.000km auf einmal exportieren will. Dann läuft nämlich der RAM voll und PHP schießt den Request ab. 😂💀 

Versuch bitte, nicht so viele Daten auf einmal rauszuexportieren, dann sollte es auch gehen :D

**Comment by Trexmex** [comment]
Alles klar, in die Richtung dachte ich schon. Danke fürs nachschauen!

**Comment by MrKrisKrisu** [comment]
Wir sollten das auf jeden Fall aber technisch irgendwie limitieren. Zeitlich? Anzahl Exporte? Sowas sollte nicht zu einem RAM-overflow führen.

**Comment by MrKrisKrisu** [comment]
Ich sehe das Issue mit dem PR #1129 als gelöst, da wir hier den Exportzeitraum + Anzahl etwas einschränken. Mehr RAM zuweisen sehe ich nicht als nötig an.
