### ISSUE TITLE
Active Statuses page is slow and sluggish.

### ISSUE THREAD

**Issue by jeyemwey** [Traewelling/traewelling#1113]
Die "Unterwegs"-Seite ist ganz schön langsam und unperformant, wenn viele Leute (z.B. `>50`) unterwegs sind. Mir sind ein paar Dinge aufgefallen:

1. Der Seitenaufbau ist ziemlich langsam (bei mir gerade `>13s`)
2. Die Seite alleine (ohne Assets) ist knapp 7MB groß, davon 6.5MB durch Pfad-Daten.
3. Die Leaflet-Karte und das Path Rendering verbraten unendlich viele CPU-Cycles. Wenn man die Karte aus dem HTML rauslöscht, sind meine Rechner damit zufrieden.

Dafür sieht die Karte so halt auch ziemlich nice aus.

<img src="https://user-images.githubusercontent.com/2796271/196035010-d95e3f17-922a-4b42-aa4d-d00579cbddd8.jpg" alt="Aktuelle Livekarte mit sehr sehr vielen Linien" width=400 />

Der Code für die Livekarte ist wahrscheinlich seit 3 Jahren nicht mehr angefasst worden, als wir noch sehr viel weniger User hatten. Ich hab noch keine sinnvolle Idee, wie wir den Load reduzieren können, bin aber für alles offen.

**Comment by MrKrisKrisu** [comment]
The map is also sometimes so buggy that the javascript stops rendering at some point, because of syntax errors. Then it is incomplete. If I see the error again I copy the message.

**Comment by jeyemwey** [comment]
Dunno if this helps, but Leaflet offers a "preferCanvas" flag, maybe it will become better with this? https://leafletjs.com/reference.html#map-prefercanvas

**Comment by NyCodeGHG** [comment]
The active statuses page seems to make a huge amount of queries.
I tested locally with 62 active checkins, that the page makes 445 queries for the initial page load.
I think this could be optimized down to very few queries
