### ISSUE TITLE
Destination station not delivered by API

### ISSUE THREAD

**Issue by jheubuch** [Traewelling/traewelling#1128]
**Describe the bug**
In case of delays, sometimes the last stop of a journey isn't delivered by API

**Screenshots**
API:
![-938oa.jpg](https://user-images.githubusercontent.com/60344409/197179446-14b5283d-d2e4-481b-9d7a-cce693110eda.jpg)

Trwl-Wrbsite:
![wdt2bl.jpg](https://user-images.githubusercontent.com/60344409/197179488-aa656c8b-fba3-45ad-bed4-8c6f1ceb3abc.jpg)

**Comment by jeyemwey** [comment]
Might be connected to #1126 which is resolved in #1127.

Please check after the changes have been deployed and thanks to @Taskplays [who made the connection](https://twitter.com/bendixdev/status/1583435613818134528). I will keep the issue open until the changes have been deployed.

**Comment by MrKrisKrisu** [comment]
#1127 is rolled out. Please let us know when this comes back up.
