### ISSUE TITLE
API endpoint for getting personal current check-in state

### ISSUE THREAD

**Issue by jheubuch** [Traewelling/traewelling#1158]
As an API user I want to query my current check-in-state.
This could be an endpoint like `/auth/user/now` which returns e.g.:

- 200 with an status object if the (logged-in) user is currently en-route with an active status
- 404 if the user has no active check-in

**Comment by MrKrisKrisu** [comment]
I'm not sure, if I would create an extra endpoint for this. Is the endpoint `v1/user/{username}/statuses?limit=1` not suitable for you? You'll get the newest status from the user and can locally check if this is enroute or in the past.

**Comment by jheubuch** [comment]
Ah, didn't know that there is this Query-Param you can pass.
I think the problem for me would here be, that you can't request the active check-in state without having a username.

So if you only have stored the bearer token locally (and not the username), you first need to request the current user via `/auth/user` and then could request the latest check-in...

Do you understand, what I try to tell? :D
