### ISSUE TITLE
PDF - Export Summen

### ISSUE THREAD

**Issue by michael-mezgo** [Traewelling/traewelling#1174]
**Is your feature request related to a problem? Please describe.**
Bisher werden im PDF-Export "nur" die einzelnen Verbindungen aufgelistet.

**Describe the solution you'd like**
- Einbau von Summen (Zeit, Kilometer) am Ende der Spalten im PDF-Export.
- Hier wäre optional auch eine Aufschlüsselung der Summen je nach Reiseart (Privat, Geschäftlich, Arbeitsweg) ein tolles Feature.

**Comment by jeyemwey** [comment]
Danke für den Vorschlag! Ich habe den Code mit #1187 hinzugefügt (siehe auch das Foto dadrin!). Der Code wird irgendwann in naher Zukunft ausgerollt.
