### ISSUE TITLE
API: HafasTrip: replace polyline hash with actual polyline polygon data

### ISSUE THREAD

**Issue by xanderio** [Traewelling/traewelling#119]
**Is your feature request related to a problem? Please describe.**
The HafasTrip that is returned with a status contains a `polyline` field its seams to be some datebase internal hash. This is quite useless while working with the API

**Describe the solution you'd like**
Replacing the `polyline` hash with the actual `polyline` polygon data

**Describe alternatives you've considered**
A possible alternative would be a separate endpoint to request this data, but this could create a high request load while loading multiple polylines in a frontend. A possible solution to this problem would be a API that allow to request multiple `polyline` polygon.

**Comment by HerrLevin** [comment]
The alternative has been added to the API v1: https://traewelling.de/api/documentation#/Status/getPolylines
