### ISSUE TITLE
Export trips to a geo file format

### ISSUE THREAD

**Issue by jeyemwey** [Traewelling/traewelling#1206]
**Is your feature request related to a problem? Please describe.**
As a user, I'd like to track my journeys via Träwelling, and later export my trips to other kinds of software, such as Geo-Spatial Software.

**Describe the solution you'd like**
Add an option to the exporting view, generate a file with all trips in a specified time frame. This file should contain:
* Journeys (origin, destination with date times) and additional data (status text? mode of transport? Operator?)
* Polyline data of the track, if available
* Interim stops

**Describe alternatives you've considered**
We need to research which file format is widely accepted and can contain the data. From my Geocaching days, I remember KML and GPX, but I have no idea if they're replaced by something newer/fancier/cooler/easier.

**Additional context**
* Inspired by [this thread](https://twitter.com/BehrPictures/status/1596868517756014592) that mentioned Träwelling on the side.

**Comment by MrKrisKrisu** [comment]
> We need to research which file format is widely accepted and can contain the data. 

I would prefer GeoJSON for this export.
