### ISSUE TITLE
Blockierfunktion

### ISSUE THREAD

**Issue by Deluisa** [Traewelling/traewelling#1251]
Ich habe meine Check-ins gerne öffentlich, Fahrten zu mir nach Hause aber aus gutem Grund nur für Follower sichtbar. Seit geraumer Zeit werden ich und einige andere Frauen von einem Typen penetrant verfolgt, der uns, auch wenn wir ihn aus unseren Followern schmeißen, immer wieder folgt. Auch auf anderen Plattformen mussten wir ihn bereits blockieren.
Für unsere Sicherheit ist eine Funktion einzelne User nach übergriffigem Verhalten blockieren zu können enorm wichtig.

**Comment by MrKrisKrisu** [comment]
Thanks for reporting.

Implemented with https://github.com/Traewelling/traewelling/commit/c239d61db8607728015f33f92eeb54724f072e84
We will roll this out soon. We love the hear from you, if there are any other problems.
