### ISSUE TITLE
Betreiber auslesen bei Bussen des DB Konzern

### ISSUE THREAD

**Issue by jeli2312** [Traewelling/traewelling#1267]
Hallo, 
leider kenne ich die aus RIS gelieferten Daten für die benutzte Schnittstelle nicht. 

Im RIS sind grundsätzlich aber für Busse der DB (Beispiel Stadtbusse in Pforzheim) auch die Betreiber angegeben. (Ich bin DB Mitarbeiter und sehe die Betreiberangaben) 

Es wäre cool, wenn man diese auch auslesen könnte und in die Statistik mit einbeziehen. 

Viele Grüße 

Christian

**Comment by MrKrisKrisu** [comment]
Mir sind leider keine Schnittstellen bekannt, wo man das öffentlich auslesen kann. Viele Busse werden einfach nur unter dem Operator "Nahreisezug" geführt. Die Daten im RIS sind ja leider nur intern und können/dürfen nicht verwendet werden.

Gerne bescheid sagen, wenn jemand hier mehr Schnittstellen kennt, dann würde ich das Issue wieder öffnen.
