### ISSUE TITLE
Hover effect on "Last station" buttons is broken

### ISSUE THREAD

**Issue by pReya** [Traewelling/traewelling#1283]
**Describe the bug**
- When the two buttons next to the "last station" input on the start page are hovered, the border disappears (tested in latest Chrome and Firefox on macOS)
- Icons inside these buttons are not centered correctly

**Expected behavior**
Border should not disappear on hover.

**Screenshots**
<img width="263" alt="Screenshot 2023-01-07 at 11 42 04" src="https://user-images.githubusercontent.com/4677417/211146441-35f1d84e-c21d-4d34-ac7c-81e81ed68e38.png">

**Comment by MrKrisKrisu** [comment]
This seems to have been broken during the last mdbootstrap update.

**Comment by tobiasreinhard** [comment]
Maybe replace the custom button "btn-outline-grey" with "btn-outline-dark" or add a custom :hover-property to "btn-outline-grey" in the "custom-button.scss"-file.
