### ISSUE TITLE
Progressbar and date missing.

### ISSUE THREAD

**Issue by HerrLevin** [Traewelling/traewelling#130]
**Describe the bug**
The progressbar and date will not show up in the active statuses or the profile page if you're not logged in.

**To Reproduce**
1. Log out
2. Go to "en route" or a profile page

**Screenshots**
Logged in:
![Screen Capture_select-area_20201005105059](https://user-images.githubusercontent.com/1267894/95059159-d0d1d280-06f8-11eb-825a-215117a82fae.png)
Logged out:
![Screen Capture_select-area_20201005105052](https://user-images.githubusercontent.com/1267894/95059161-d0d1d280-06f8-11eb-9a59-6eba9cee1304.png)

**Expected behavior**
See the progress bar progressing and the date above the status.

**Desktop (please complete the following information):**
 - OS: Arch Linux (5.8.12-arch1-1)
 - Browser Chromium
 - Version 85.0.4183.121 (Official Build) Arch Linux (64-bit)

**Comment by MrKrisKrisu** [comment]
I fixed the Headings in #132. But I cannot reproduce the error (in the current version of the develop branch) with the progress bar. This is working for me.

But I have disabled the Headings at the active statuses page because there are only... statuses from now? So why print a date?
