### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by NyCodeGHG** [Traewelling/traewelling#1301]
**Is your feature request related to a problem? Please describe.**

When a third party application wants to know if a user did something on the platform (e.g. created a status, updated a status etc.), it currenlty must poll the data to do that.
Polling leads to high traffic.

**Describe the solution you'd like**

Webhooks integrated into the existing system for third party applications.

I thought about creating api endpoints to create a webhook specific to a user.

**Describe alternatives you've considered**

Keep polling, but that would be bad for both third parties and traewelling because the traffic would be much higher here.

**Additional context**

I'm not that fluent in php but I would like to try to work on that feature. I just wanted to open this issue before i invest to much time into it and it won't get merged :)

**Comment by jeyemwey** [comment]
Hi! We have already tried on working on Webhooks in #987, but found a number of road blocks (OAuth2-Apps were not a thing back then, there was no event handler and even the Twitter/Masto Postings were done synchronously).

If you want to work on it, I think that taking a look at the code in #987 is a good starting point, although I'd love it if you gave it your own spin. Go right ahead and we'll guide you :)
