### ISSUE TITLE
Add ability to check in "Groups" of people at once

### ISSUE THREAD

**Issue by ChillLP** [Traewelling/traewelling#1302]
General idea is that it works like a Whatsapp group, you invite people into that group and for the set timeframe every check-in will be Mirrored for the others.
this would make träwelling in groups a whole lot easier and you wouldnt have to send each user a new notification (maybe send them one saying "Your group host checked in" or something along the lines) that the same people are on that specific train ride, rather send others on that ride a message saying "Group xyz is also on your ride" and when clicking opening that notification they can see who is in that group and where they are headed. 

![image](https://user-images.githubusercontent.com/105374102/212931911-ba3f7b24-a68c-4dd2-9096-5239587ae1d4.png)

**Comment by ChillLP** [comment]
I dont know why, but For Some reason this issue isnt shown in the issues Page?

**Comment by MrKrisKrisu** [comment]
> I dont know why, but For Some reason this issue isnt shown in the issues Page?

![image](https://user-images.githubusercontent.com/4103693/215471692-7b0434fe-2812-4cff-9029-09086e080c81.png)

**Comment by ChillLP** [comment]
Visible Confusion.
