### ISSUE TITLE
Alertbox breaking Design and is not closeable when I block someone

### ISSUE THREAD

**Issue by SoraCent** [Traewelling/traewelling#1305]
**Describe the bug**
When I block someone there is an Alertbox showing that I blocked the user.
This Alertbox is not closeable by pressing the X Button and is breaking the Design of the Profilepage

**To Reproduce**

1. Go to 'Someones Profile'
2. Click on 'Block User'
3. See the Alertbox
4. Try to close the Alertbox

**Expected behavior**
The Alertbox shouldn't break the Design and should be closeable

**Screenshots**
![grafik](https://user-images.githubusercontent.com/46794893/213461837-c1029a1a-2d0e-4dc6-b316-b41fcccc5e09.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox / Edge
- Version: Firefox 108.0.2 / Edge 109.0.1518.55

**Smartphone (please complete the following information):**

- Device: Huawei P30 Pro (New Edition)
- OS: Android Q (10)
- Browser: Firefox Beta
- Version: 109.0b6

**Additional context**
Happens for other users too

Happens also when I unblock someone

**Comment by Oxbowatos** [comment]
Ich kann diesen "Bug" bestätigen

**Comment by Oxbowatos** [comment]
Habe das selbe Problem bei anderen Notifications, wenn man keine Station eingegeben hat als beispiel.
Wenn man auf X klickt werden die Notifications nicht geschlossen.
![grafik](https://user-images.githubusercontent.com/123954576/215763275-c4bfe4f5-1ea0-4246-9581-a82f1f84d091.png)

**Comment by vainamov** [comment]
#1372 sollte dafür sorgen, dass Alerts wieder geschlossen werden können. An dem "kaputten" UI ist das negative Margin aus https://github.com/Traewelling/traewelling/blob/60fb0cb3d7a84cd43ed4a07aa660d9be42ce3e46/resources/views/profile.blade.php#L17 Schuld, aber mir fällt aktuell keine schicke Lösung ein, um das Problem zu beheben. Vielleicht sollte man Alerts eher schwebend am Rand positionieren?

**Comment by MrKrisKrisu** [comment]
> Vielleicht sollte man Alerts eher schwebend am Rand positionieren?

Wir haben bereits das npm package `notyf` installiert und an ein paar wenigen Stellen eingesetzt. Damit landen die Notifications oben rechts in einem Popup. Ggfs. können manche Alerts dadurch ersetzt werden. Ist dann nur etwas doof mit dem Pagerefresh.
