### ISSUE TITLE
Create mute returns HTTP 500

### ISSUE THREAD

**Issue by DRSchlaubi** [Traewelling/traewelling#1317]
**Describe the bug**
create mute returns 500

**To Reproduce**
Make an API call to https://traewelling.de/api/v1/user/createMute?userId=1324

**Comment by HerrLevin** [comment]
Sorry for the late response. The endpoint structure for muting changed in [v1.26](https://github.com/Traewelling/traewelling/releases/tag/v1.26) / #1275.

With the new endpoints everything works for me. Please confirm and I'll close the issue. :)

see also: https://traewelling.de/api/documentation#/User%2FHide%20and%20Block/createMute

**Comment by HerrLevin** [comment]
(Please note: always consult the API documentation at https://traewelling.de/api/documentation if sth breaks unexpectedly. As long as v1 is not completely finished, endpoints might change without any warning. We're trying to inform about any changes to critical endpoints but always might forget something)

**Comment by DRSchlaubi** [comment]
> Sorry for the late response. The endpoint structure for muting changed in [v1.26](https://github.com/Traewelling/traewelling/releases/tag/v1.26) / #1275.
> 
> With the new endpoints everything works for me. Please confirm and I'll close the issue. :)
> 
> see also: https://traewelling.de/api/documentation#/User%2FHide%20and%20Block/createMute

But it wasn't mentioned in the PR description, you should probably update that
