### ISSUE TITLE
500 on creating non-confidential OAuth application

### ISSUE THREAD

**Issue by jheubuch** [Traewelling/traewelling#1318]
Träwelling throws 500 when you try to create a new application with non-confidential credentials.

1. Open dev portal
2. Create new application, fill in details, unselect "Confidential"
3. Press "Create"
4. See crashing locomotive

**Comment by jheubuch** [comment]
Maybe also interesting for @NyCodeGHG? :)

**Comment by NyCodeGHG** [comment]
i also brought this on topic on discord. I don't remember who, but someone said that the secret database column is for whatever reason not nullable in the production database. At least on my machine, when i run the Migrations, everything works fine and the column is nullable, as it should

**Comment by jheubuch** [comment]
ouff, dang it. Thanks for the information!

**Comment by MrKrisKrisu** [comment]
This was due to an incomplete migration of Passport. We are using Passport v11, but it was missing a migration from the upgrade from v7 => v8.

https://github.com/laravel/passport/blob/11.x/UPGRADE.md
