### ISSUE TITLE
Pagination too Big for Mobile Screens

### ISSUE THREAD

**Issue by SoraCent** [Traewelling/traewelling#1322]
**Describe the bug**
The Pagination on the Profile is too big for Mobile Screens if there are too many Pages and breaks the Design

**To Reproduce**

1. Go to 'A Profile that has a lot of Checkins
3. Scroll down to 'The Bottom'
4. If a Profile has a lot of Checkins the Pagination is breaking the Design in width.

**Expected behavior**
The Pagination's width shouldn't break the Width of the Website and also should be more optimized for Mobile devices

**Screenshots**
![grafik](https://user-images.githubusercontent.com/46794893/214557680-7b4d4178-060c-4eb0-acf8-14b6db353ce2.png)
![grafik](https://user-images.githubusercontent.com/46794893/214557709-f91d60d3-9309-4210-ac52-2467742abbbb.png)

**Smartphone (please complete the following information):**

- Device: Huawei P30 Pro (New Edition)
- OS: Android Q (10)
- Browser: Firefox Beta
- Version: 109.0b6

and:

- Device: Huawei P20 Pro
- OS: Android Q (10)
- Browser: Brave (Chromium)
- Version: 1.47.175

**Additional context**
-

**Comment by ChillLP** [comment]
Smartphone 

Device: Samsung Galaxy S22+ and S10+
OS: Android 13 and 12
Browser: Opera for Mobile


Can confirm, happens on other Browsers too

**Comment by Mayuresh0072** [comment]
@MrKrisKrisu Hello, I want to work on this issue and contribute.. Please assign me this issue. Thanks

**Comment by MrKrisKrisu** [comment]
> @MrKrisKrisu Hello, I want to work on this issue and contribute.. Please assign me this issue. Thanks

Feel free to work on the issue without assignment and create a PR. :)

Laravel's pagination feature should have the ability to limit the number of subpages displayed. Possibly that would be a good approach.

**Comment by Mayuresh0072** [comment]
@MrKrisKrisu Actually, Solving issues is part of college assignment. So, It would be very helpful for me  if you assign me, so that i can show my progress. Thanks
