### ISSUE TITLE
Website in German even if language preference is English first

### ISSUE THREAD

**Issue by dancojocaru2000** [Traewelling/traewelling#1323]
**Describe the bug**
When I go to the website, it appears in German, despite my browser preferences being English first and my `Accept-Language` header being `en-GB,en-US;q=0.9,en;q=0.8,ro;q=0.7,de;q=0.6`.

**To Reproduce**
Not quite sure to be honest. I'm just going to [traewelling.de](https://traewelling.de).

**Expected behavior**
Website should appear in English.

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS
- Browser Vivaldi
- Version 5.6.2867.58 (Stable channel) (arm64) 

**Additional context**
This may be because I have a German IP and the website is taking only that into account?

**Comment by DRSchlaubi** [comment]
I think the website ignores the `Accept-Language` header alltogether

**Comment by MrKrisKrisu** [comment]
The following code should actually set the language depending on the header, unless other conditions before have already set that.

Are you logged in? If yes, then your language is stored in your account and the browser settings don't matter.

https://github.com/Traewelling/traewelling/blob/f398dfc44899e16ba370d22e53e30cd2cc8d8a22/app/Http/Middleware/Language.php#L50-L63

**Comment by DRSchlaubi** [comment]
I wasn't logged in

**Comment by dancojocaru2000** [comment]
Likewise, it was my first visit to the page and the page appeared in German.

Tried just now from my phone and the page also appears in German.
