### ISSUE TITLE
"En Route" lagging and not loading

### ISSUE THREAD

**Issue by Oxbowatos** [Traewelling/traewelling#1342]
**Describe the bug**
"En Route" is not optimized, lagging, takes long to load or doesn't load and breaking the Browser

**To Reproduce**

1. Go to 'En Route'

**Expected behavior**
The Page should be loaded faster.

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Firefox
- Version Newest

**Comment by jeyemwey** [comment]
Thanks for the feedback. This looks like a duplicate of #1113, so I'd like to merge the two together.
