### ISSUE TITLE
Line Breaks for Checkin Descriptions instead of own Seperators

### ISSUE THREAD

**Issue by Oxbowatos** [Traewelling/traewelling#1349]
**Is your feature request related to a problem? Please describe.**
It would be nice if the Checkin Description allows Line Breaks. I write a lot of Informations in it and to seperate it I need to use |, I also saw others using the - to seperate it.

**Describe the solution you'd like**
The Description is already a Textarea Input so it should be easy to allow the line breaks which can be made in Textareas so users don't need to use special seperators like - or | to seperate a sentence.

**Comment by MrKrisKrisu** [comment]
Linebreaks are already supported. We just don't render them with a html breaking character. So I would change this issue to an "bug report".

**Comment by SoraCent** [comment]
Soweit ich weiss sollte CSS reichen.
Ein Textarea speichert die newlines als \n oder \r\n oder \r und mit CSS kann man beim Paragraph mit der Klasse Status-body einfach "white-space: pre-line" definieren und dies sollte die line breaks dann auch anzeigen.

**Comment by Oxbowatos** [comment]
@SoraCent wirst du es denn einfügen ?

**Comment by SoraCent** [comment]
@Oxbowatos Ich kann es leider nicht hinzufügen da Träwelling bei mir Lokal weder auf meinem Windows noch Linux gerät funktioniert somit kann ich es nicht anpassen. Aber eigentlich muss jemand nur in "resources/sass/site.scss" die Zeile
`
ul.timeline > li p.status-body {
    white-space: pre-line;
}
`
hinzufügen und schon gehen die Line Breaks
