### ISSUE TITLE
Map: Add OpenRailwayMap Layer

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/traewelling#1359]
**Describe the solution you'd like**
I would like to have a possibility to **_optionally_** activate an overlay of OpenRailwayMap in the settings. This is to display the ORM Infrastructure Overlay over all maps displayed on traewelling.de.

**Describe alternatives you've considered**
none

**Additional context**
- [ORM Tiles](https://wiki.openstreetmap.org/wiki/OpenRailwayMap/API#Tiles)
- Add license notice

**Comment by ErikUden** [comment]
~~Just wanted to point out that the implementation could be taken from Travelynx as they've added the feature a while ago.~~

~~https://github.com/derf/travelynx~~

Nonsense, they didn't add it. I was thinking of something else.
