### ISSUE TITLE
Timepicker should open when you press the Input instead only the Icon

### ISSUE THREAD

**Issue by Oxbowatos** [Traewelling/traewelling#1375]
**Is your feature request related to a problem? Please describe.**
Rightnow when I press on the timepicker Input the first Number is focused and no keyboard input is working, to change the date you need to press on the Calendar Icon to open the Timepicker.

**Describe the solution you'd like**
I would like that the Datepicker also opens when I press on the whole Input not only the Icon.

**Describe alternatives you've considered**
If that is not possible make it possible to write a date manually in the input.

**Additional context**
"When I press on the Input only the numbers get highlighted" 
![grafik](https://user-images.githubusercontent.com/123954576/217193428-d23b1217-b442-4f3a-95b0-abff0e010744.png)

**Comment by HerrLevin** [comment]
This is the browsers default behavior. This issue should be redirected to firefox.
