### ISSUE TITLE
Checkin Profilepic vanishing if someone likes own Checkins (Mobile)

### ISSUE THREAD

**Issue by Oxbowatos** [Traewelling/traewelling#1377]
**Describe the bug**
If someone likes your checkin the Profilepic is getting removed in the Mobileversion of the Website.

**To Reproduce**

1. Create a new Checkin
2. Someone Likes it or you Like it
3. Make the Window Smaller or change to Mobile
4. See that the Profile has vanished (in comparison with other Checkins without Likes)

**Expected behavior**
The Profilepic shouldn't be removed

**Screenshots**
![grafik](https://user-images.githubusercontent.com/123954576/217222063-60fcb6ac-92f2-4f0a-aff7-384f645230b1.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Firefox
- Version: Newest

**Smartphone (please complete the following information):**

Private Phone:
- Device: IPhone 14 Pro Max
- OS: IOS 16.3
- Browser: Safari
- Version: Newest

Work Phone:
- Device: Samsung Galaxy S22 Ultra
- OS: Android 13
- Browser: Firefox & Firefox Nightly
- Version: Newest

**Comment by jeyemwey** [comment]
I worked hard and sweaty so that worked exactly the way it does. But I understand that it isn't necessary with the increasing width of phones.

**Comment by Oxbowatos** [comment]
My IPhone 14 Pro Max and Samsung Galaxy S22 Ultra have big Screenwidths and there isn't any Bigger phone (Except the Samsung Fold Phablets).
And because it's only happening on own Checkins and only when it's liked than it counts as Bug also as bad Optimized for Mobile because such bugs shouldn't happen on any Device.

Because the breakpoint to mobile is on 720px Width it could also occur on Tablets.

**Comment by SoraCent** [comment]
Can confirm that this happens on my Huawei P30 Pro and if you make your Desktop Browser smaller
