### ISSUE TITLE
A better way using Travel-Type (Private, Business, Commute) and Events checkins

### ISSUE THREAD

**Issue by Oxbowatos** [Traewelling/traewelling#1378]
**Is your feature request related to a problem? Please describe.**
A clear problem is that users misuse the Travel-Types and Events.
I already saw multiple users using the Travel-Type "Commute" for every check-ins even if that isn't their way to work/school and others check-in to Events with random check-ins, e.g. A Event in Hamburg: peoples check-in a route from München to Wien and also check that they travel because of the event without even going near to the Event's designated place (neither with other check-ins), I also saw that misuse with the 9€ Ticket event last summer.

**Describe the solution you'd like**
I don't know a good Solution at the moment that's why this needs more discussion

**Describe alternatives you've considered**
An alternative would be to remove those options so no one can misuse those.

**Comment by ChristianTacke** [comment]
May I ask how this affects you?

**Comment by NyCodeGHG** [comment]
I think there could be ways to improve the UX so users are less likely to forget to select the correct options.
Something like:
- User is not near event in like 50km radius, transport type is not long distance -> ask if they are sure
- User is near event (same radius) -> don't ask
- User is not near event but transport type is long distance and destination will bring them near -> don't ask

But removing the options just because some people are doing mistakes is not for debate i guess.

**Comment by jeriox** [comment]
Another aspect that I am missing: there are two different meanings for "work" right now. Users use this to indicate that they are working the respective train (e.g. as Triebfahrzeugführer) as well as using the train _on their work time_ e.g. as a business trip (Dienstreise). It would be great to be able to differentiate between those two.

**Comment by HerrLevin** [comment]
With the introduction of tags, this issue has lost any relevance.

**Comment by HerrLevin** [comment]
With the introduction of tags, this issue has lost any relevance.

**Comment by marhei** [comment]
> Another aspect that I am missing: there are two different meanings for "work" right now. Users use this to indicate that they are working the respective train (e.g. as Triebfahrzeugführer) as well as using the train _on their work time_ e.g. as a business trip (Dienstreise). It would be great to be able to differentiate between those two.

I think using tags with a new tage key like "role" could be used to indicate the function on the train (like Tf, Zf, Gastfahrt…)
