### ISSUE TITLE
Hashtags or tags Support for Checkins & Search function

### ISSUE THREAD

**Issue by Oxbowatos** [Traewelling/traewelling#1383]
My Idea is that it's possible to add Hashtags or normal tags to the Checkins through the Checkinmessage or a seperate input and by adding this we can think about a search function for checkins not only users.

Like on Twitter you could search for an Hashtag and every checkin with the hashtag is showing up.

With combination of Issue #1350 you can add Hashtags in there too and search profiles with hashtags.

**Comment by HerrLevin** [comment]
Closed with #1249
