### ISSUE TITLE
Implement Web Share API

### ISSUE THREAD

**Issue by jeyemwey** [Traewelling/traewelling#1384]
With Twitter dropped from Träwelling, it would be great to have a generic option to share information. The Web Share API can solve this for us, as it hooks into the native share sheet of the OS.

We cab create a button that launches the Share Sheet from the "Check-in Success" flash message.

A similar feature has been implemented by our friends at Retrospring.

More Info:
* https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share
* https://www.w3.org/TR/web-share/

**Comment by NyCodeGHG** [comment]
because the web share api is still a draft, it's not yet supported by firefox. So it would be great to have a "copy link" fallback when web share is not available

**Comment by jeyemwey** [comment]
Here's my current design, but not sure if that's great.

![Screenshot with the new button](https://user-images.githubusercontent.com/2796271/217791907-f5089c5b-9f30-4d41-8158-8e91f6d1d4a6.png)


> So it would be great to have a "copy link" fallback when web share is not available

Do you just need a [copy button](https://fontawesome.com/icons/copy?f=classic&s=regular) or would you want an input field where you can copy the text yourself?

**Comment by NyCodeGHG** [comment]
i would let it be the same button and just check in js if `navigator.share` is not undefined

e.g.
```js
const url = "blabla";
if (navigator.share) {
  navigator.share({ url, title: "Meine Reise in STR 1 auf Träwelling" }).catch(e => {
    // handle error and maybe fall back to clipboard based on the error?
    // see https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share#exceptions
  });
} else {
  navigator.clipboard.writeText(url);
  // send notification copied to clipboard
}
```

**Comment by ChristianTacke** [comment]
After a successful checkin one usually ends up on the global dashboard (which currently is a little slow). Maybe instead one should end up on exactly the URL that would be shared? That way the builtin share/copy features of the browsers would also work somewhat?

**Comment by HerrLevin** [comment]
> Here's my current design, but not sure if that's great.

This looks fine, but i think the visibility will suffer once you're checking in w/ multiple people. If you want to, a complete redesign of the checkin success prompt would fix that. Maybe sth like a small coloured modal? Kinde like this example taken out of https://mdbootstrap.com/docs/standard/components/modal/
![grafik](https://user-images.githubusercontent.com/1267894/217813164-9edc535a-02ae-473b-903e-efb4c2b70685.png)

**Comment by HerrLevin** [comment]
> After a successful checkin one usually ends up on the global dashboard (which currently is a little slow). Maybe instead one should end up on exactly the URL that would be shared? That way the builtin share/copy features of the browsers would also work somewhat?

I like that idea but this might break the checkin flow a bit, since you'll be back on the status page once you reopen your browser/open the "PWA". We might need to test that.
