### ISSUE TITLE
Bei aktiviertem "Teilen via Mastodon" können keine Fahrten mehr gepostet werden. Wenn man Sharing via Mastodon beim Posten

### ISSUE THREAD

**Issue by ColaDeveloper** [Traewelling/traewelling#1393]
Bei aktivierten "Telen auf Mastodon" können keine Fahrten mehr gepostet werden.

Wenn man Mastodon beim Verfassen des Beitrags deaktiviert, funktioniert das Teilen des Beitrags ganz normal.

![image](https://user-images.githubusercontent.com/73913907/218294665-d97fa743-388d-4c23-8dcc-bdb7b9c2e1c7.png)

**Describe the bug**

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jheubuch** [comment]
Can confirm. Same for me. API is throwing "500"

**Comment by HerrLevin** [comment]
Fixed!
