### ISSUE TITLE
"Last station" option doesn't open

### ISSUE THREAD

**Issue by Oxbowatos** [Traewelling/traewelling#1401]
**Describe the bug**
When I press "Last stations" the "dropdown" gets closed and I get two Errors (see screenshots)

**To Reproduce**

1. Go to 'Dashboard'
2. Click on 'Last stations' button (Clock next to the input field)
3. See how the Dropdown opens but closes again
4. See errors

**Expected behavior**
The Dropdown should be opened and no Error should be displayed

**Screenshots**
![grafik](https://user-images.githubusercontent.com/123954576/218454912-d75da3d4-7f0f-4d22-b9dd-87f75f60d6a7.png)

**Desktop (please complete the following information):**

- OS: MacOS 13
- Browser: Safari
- Version: 16.2

and

- OS: Windows 11
- Browser: Firefox
- Version: 109.0.1

**Smartphone (please complete the following information):**

Private Phone:

- Device: IPhone 14 Pro Max
- OS: IOS 16.3
- Browser: Safari
- Version: Newest

Work Phone:

- Device: Samsung Galaxy S22 Ultra
- OS: Android 13
- Browser: Firefox & Firefox Nightly
- Version: Newest

**Comment by DRSchlaubi** [comment]
Sounds like a specific station on your history does not have an ibnr?

Okay happens to me as well, but it works when using the API

**Comment by SoraCent** [comment]
Happens to me too on my Huawei VOG-L29 (Huawei P30 Pro) on Chrome version 110.0.5427.64

**Comment by jheubuch** [comment]
> Sounds like a specific station on your history does not have an ibnr?
> 
> Okay happens to me as well, but it works when using the API

When clicking the "history" button, the stationboard page is called without a station name/ibnr:
![image](https://user-images.githubusercontent.com/60344409/218569529-9c42c29f-0702-4b75-8399-1b20c6b29abd.png)

I guess, this is the not expected behaviour.
