### ISSUE TITLE
"Punkte" Icon Missing (?)

### ISSUE THREAD

**Issue by ChillLP** [Traewelling/traewelling#1405]
**Describe the bug**
Looking at my daily stats the Icon for "Punkte" is Missing/Not shwon correctly

**To Reproduce**

1. Go to Your profile
2. Click on your daily stats
3. Scroll down to Your Points 

**Expected behavior**

**Screenshots**
![Screenshot_20230215_120802_Opera.jpg](https://user-images.githubusercontent.com/105374102/219012094-e58ea44b-67b6-4db3-bafe-5dc959c1044c.jpg)

]

- Device: Galaxy S22+
- OS: Android 13
- Browser Opera GX Mobile
- Version newest

**Additional context**

**Comment by Oxbowatos** [comment]
Missing for me too 
![grafik](https://user-images.githubusercontent.com/123954576/219021669-763c4cca-b788-45d3-bf87-502a1daa924d.png)
