### ISSUE TITLE
Language cannot be changed on the home page

### ISSUE THREAD

**Issue by DC7IA** [Traewelling/traewelling#1409]
**Describe the bug**
I chose bug since this affects the user experience.

To choose the language, you first have to click a link, then change the language on another page, which is confusing for user that do not understand German.

**Expected behavior**

Home page should include a way to change the language.

**Comment by HerrLevin** [comment]
Generally this shouldn't be a problem, since we're showing the preferred browser language if you're not logged in. But we could consider adding this in #1131. I'll change this ticket to enhancement.
