### ISSUE TITLE
Zeitdaten bei Check-Ins.

### ISSUE THREAD

**Issue by oepnvspotterjannik** [Traewelling/traewelling#1433]
**Is your feature request related to a problem? Please describe.**
Die Echtzeitdaten stimmen öfters nicht. 
Es wird in den Check-Ins teilweise verspätung angezeigt obwohl man pünktlich ist, bzw auch angezeigt das man pünktlich war obwohl man zu spät war

**Describe the solution you'd like**
Das man einmalig die Chance hat, eine tatsächliche Abfahrts- und Ankunftszeit einzugeben beim bearbeiten des Check-Ins.

**Describe alternatives you've considered**
Ich glaube nicht das es eine einfache Alternativemöglichkeit gibt.

**Comment by ChillLP** [comment]
Die daten Stammen aus der HAFAS schnittstelle der DB, ich glaub nicht dass das Träwelling team da besonders viel machen kann
