### ISSUE TITLE
Manuelle Korrektur von Streckenkilometern

### ISSUE THREAD

**Issue by marhei** [Traewelling/traewelling#1441]
In Anlehnung auf das PR #1439 von @MrKrisKrisu wäre eine manuelle Korrektur der Streckenkilometer denkbar.

Im Ausland wird vom Hafas kein direkter Laufweg geliefert und dadurch werden die Streckenkilometer natürlich auch nur mit der Luftlinie zwischen den Unterwegshalten berechnet.

Zusätzlich könnte man vielleicht auch eine Erkennung solcher fehlenden genauen Kilometern einbinden und die ungenaue Luftlinienberechnung in API und Webseite besonders kennzeichnen.

**Comment by michael-mezgo** [comment]
Ich denke, dass dies nun großteils mit #1545 gelöst wurde. (Außer vielleicht für Ausflugsverkehre, welche nicht über die direkte Strecke verkehren.)
