### ISSUE TITLE
Showroom for third party applications

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/traewelling#1460]
As a developer of third party applications I would like to present my application on traewelling.de.

I imagine that in the developer settings for each created application a portfolio (image, name, description, website, support address, ...) can be specified.

If the Träwelling team has approved this presentation, it will be displayed in a showroom.

To make it non-discriminatory, the presentation of the applications should be displayed in random order.

**Comment by HerrLevin** [comment]
@MrKrisKrisu is this done with https://help.traewelling.de/community/list-of-third-party-apps/?

**Comment by MrKrisKrisu** [comment]
Oh, uhm. Yes!

**Comment by MrKrisKrisu** [comment]
Not the thing with the random order but it's okay I think.
