### ISSUE TITLE
The Global Dashboard takes a lengthy time to load. 

### ISSUE THREAD

**Issue by Oxbowatos** [Traewelling/traewelling#1465]
**Describe the bug**
The Global Dashboard is not optimized and takes a long time to load. 

**To Reproduce**

1. Click on 'Global Dashboard'
2. Observe how long it takes for the page to load. 

**Expected behavior**
The Global Dashboard should load more quickly. 

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Firefox
- Version: Newest

**Smartphone (please complete the following information):**

Private Phone:
- Device: IPhone 14 Pro Max
- OS: IOS 16.3
- Browser: Safari
- Version: Newest

Work Phone:
- Device: Samsung Galaxy S23 Ultra
- OS: Android 13
- Browser: Firefox & Firefox Nightly
- Version: Newest

**Comment by ChristianTacke** [comment]
This is somewhat annoying, because new checkins redirect to the global dashboard.

Probably in a nice way of "Okay, you entered a train? You might want to know, who else is on their ways somewhere?" – Good intention!

Maybe redirect to the status page of the just created checkin? This also might help #1384?

**Comment by HerrLevin** [comment]
@ChristianTacke This is not entirely true. Checkins are redirected to your dashboard. But if you follow some accounts on Träwelling, you'll be redirected to your personal dashboard.

But I like your idea with #1384. We'll look into it. :)

**Comment by MrKrisKrisu** [comment]
I will close this issues, as I improved the performance of private and global dashboard some days ago a little bit.
Also the user will be redirected to the status after checking in [#1810]. This will also improve the user experience as suggested by @ChristianTacke :)
