### ISSUE TITLE
Notification Pill shouldn't stop at 10

### ISSUE THREAD

**Issue by Oxbowatos** [Traewelling/traewelling#1466]
**Is your feature request related to a problem? Please describe.**
If there are more than 10 Notifications, the Notification Pill will stop counting.
On the Beta, it displays more than 10 in the Pill.

**Describe the solution you'd like**
It should not stop counting at 10 Notifications or it should display 9+ in the Pill.

**Comment by volkland** [comment]
Fixed with #1633. Thanks for the ticket tho :)
