### ISSUE TITLE
Prohibit multiple accounts 

### ISSUE THREAD

**Issue by Oxbowatos** [Traewelling/traewelling#1467]
**Is your feature request related to a problem? Please describe.**
I've already seen numerous accounts with the same name, profile images, and checkins. 

**Describe the solution you'd like**
preventing the creation of multiple accounts 

**Describe alternatives you've considered**
A more effective moderation system with moderators who can ban or close user accounts

**Comment by MrKrisKrisu** [comment]
We don't have any rules which forbids users to create multiple Accounts. So I don't see a problem here.
