### ISSUE TITLE
The Profile picture appears Pixelated even when uploaded in high quality

### ISSUE THREAD

**Issue by Oxbowatos** [Traewelling/traewelling#1468]
**Describe the bug**
The profile pictures on the Profilepage appear pixelated. 

**To Reproduce**

1. Go to 'a profile'
2. See the pixelated profile picture

**Expected behavior**
The profile picture shouldn't appear pixelated when uploaded in high quality.

**Desktop (please complete the following information):**

Any Browser

**Smartphone (please complete the following information):**

Any Browser

**Comment by MrKrisKrisu** [comment]
We are scaling down all pictures while uploading. I'm not sure if I want to change this.

What do you think? @HerrLevin @jeyemwey

**Comment by jeyemwey** [comment]
The scaling down happens for two reasons: We make sure that it is indeed an image that is uploaded, and we reduce the size for HTTP requests and file storage.


I vote to not change anything here and just life with the 300x300 image (see code in https://github.com/Traewelling/traewelling/blob/ad8021dc2b93e7a698ca8d9fac66a6e11a5e8f34/app/Http/Controllers/Backend/SettingsController.php#L47).
