### ISSUE TITLE
When scrolling, the Checkin Status Text obscures the Label

### ISSUE THREAD

**Issue by Oxbowatos** [Traewelling/traewelling#1469]
**Describe the bug**
When scrolling, the Checkin Status Text obscures the Label.

**To Reproduce**

1. Check into any Train
2. Write a long Status
3. Scroll down

**Expected behavior**
The background of the label should not be translucent. 

**Screenshots**
![grafik](https://user-images.githubusercontent.com/123954576/226903383-dddc214b-20a3-412d-9da2-3674141a0983.png)

**Comment by MrKrisKrisu** [comment]
I cannot reproduce this. Which browser are you using?

**Comment by vainamov** [comment]
Can confirm this happens in the latest stable Firefox build 111.0.1 on Windows and macOS.

![grafik](https://user-images.githubusercontent.com/11841072/226928239-d2ce0f64-7146-411e-bb98-3f7512fc4254.png)
