### ISSUE TITLE
Notify webhooks that they have been deleted

### ISSUE THREAD

**Issue by HerrLevin** [Traewelling/traewelling#1485]
As a webhook developer I want to be notified that my access has been revoked.

This could be implemented via an additional webhook event, or a specific payload in the regular webhook.

              Maybe we should notify the webhook endpoint with an event that the webhook has been deleted?

_Originally posted by @NyCodeGHG in https://github.com/Traewelling/traewelling/issues/1453#issuecomment-1475209722_

**Comment by NyCodeGHG** [comment]
I think a `webhook_revoked` event would be the best solution here.

**Comment by HerrLevin** [comment]
Moved to https://github.com/Traewelling/traewelling/discussions/2006
