### ISSUE TITLE
Max Char Count on Checkin Status not showing.

### ISSUE THREAD

**Issue by Oxbowatos** [Traewelling/traewelling#1491]
**Describe the bug**
Max Char Count on Checkin Status not showing.

**To Reproduce**

1. Go to 'Trävelling'
2. Check in a new Train or edit a Check In
3. See error

**Expected behavior**
The Counter should count up or down when adding characters.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/123954576/227536837-d4fdfbb0-c582-490c-a96c-5159082df2df.png)

All Desktops and Phones with Firefox

**Comment by vainamov** [comment]
I can't reproduce this on Firefox 111.0.1 (macOS)

<img width="489" alt="grafik" src="https://user-images.githubusercontent.com/11841072/227546892-8e9f0656-1104-40d8-9f00-bafbde310559.png">

**Comment by SoraCent** [comment]
I can reproduce this on Firefox 112.0b5 (Build #2015940219), d0b3947b74+ (Android)
But only when editing a checkin ![Screenshot_20230324_151903_org.mozilla.firefox_beta.png](https://user-images.githubusercontent.com/46794893/227550516-57e35e20-b4bd-49a1-9798-46bdf8ff01f0.png)

**Comment by vainamov** [comment]
@SoraCent good point, on editing the issue occurs for me as well.
