### ISSUE TITLE
Can't check into trains around Truro, UK

### ISSUE THREAD

**Issue by Sorunome** [Traewelling/traewelling#1511]
**Describe the bug**
Soru can't seem to check into trains around Truro, UK

**To Reproduce**

1. Go to e.g. Truro https://traewelling.de/trains/stationboard?station=Truro
2. Click on any train, e.g. https://traewelling.de/trains/trip?tripID=1%7C118823%7C4%7C80%7C31032023&lineName=37580&start=7002266&departure=2023-03-31T12%3A15%3A00%2B01%3A00
3. The train route (individual stations) do not display and you can't check in to them.

**Expected behavior**
Checkin should work

**Desktop (please complete the following information):**

- OS: Fedora Kinoite
- Browser: Firefox
- Version: 111.0 (Flatpak)

**Additional context**
It worked a few days ago, but understanding timezones was a hassle so soru checked in and deleted journeys here and there

**Comment by MrKrisKrisu** [comment]
> It worked a few days ago

It is interesting that it seems to have worked a few days ago. Upon investigation, it appears that the stopovers are not being displayed because they are in the past (+1) relative to our timezone (+2).

![image](https://user-images.githubusercontent.com/4103693/229305292-a9d15852-f6b2-4aaf-a982-dd076ba6552d.png)

**Comment by Sorunome** [comment]
Hmm, soru got the issue both on her phone which was at +1 and her laptop at +2

**Comment by MrKrisKrisu** [comment]
The timezone on your device is not relevant for this. This is rendered server side.

**Comment by TheJRB** [comment]
I notice that, where there are stops more than an hour away, if you select one of these, you can then edit the destination post check-in. Just a workaround for those trains which exceed one hour end to end.

A permanent solution would be very much appreciated though!

**Comment by HerrLevin** [comment]
This should be fixed with #1693 (not our weird timezone offset but the ability to check in)

I'll close the issue for now. Pls update if it's still broken.
