### ISSUE TITLE
Departures for some (foreign?) Stations can't be queried

### ISSUE THREAD

**Issue by bendix-dev** [Traewelling/traewelling#1514]
**Describe the bug**
The departure for some (foreign) stations aren't queried correctly as the backend displays departures for a different station. Both of the examples I have can't be found through autocompletion but they are existent in train stopovers or via the "Nearby" endpoint.

**To Reproduce**
Two problematic stations are:

`Odense Banegård (Letbane)` results in `Odense Rosengårdscentret (Letbane)`
https://traewelling.de/trains/stationboard?station=Odense+Banegård+%28Letbane%29

`Wien Mitte-Landstraße Bf (U3)` or `Wien Mitte-Landstraße Bf (U4)` results in `Darmstädter Landstraße Mitte, Frankfurt a.M.`
https://traewelling.de/trains/stationboard?station=Wien+Mitte-Landstraße+Bf+%28U3%29

**Expected behavior**
The departures for the queried station are shown.

**Comment by MrKrisKrisu** [comment]
We currently use the search function of [DB-Rest](https://github.com/derhuerst/db-rest), which we do not have control over. We suggest that you create an issue on the [DB-Rest GitHub page](https://github.com/derhuerst/db-rest), as he may be better equipped to handle this issue. However, please note that DB-Rest only accesses data from the Deutsche Bahn HAFAS, so it may not be possible for him to address the issue for the foreign stations you mentioned.
