### ISSUE TITLE
Disable visibility of likes

### ISSUE THREAD

**Issue by niklasnet** [Traewelling/traewelling#1515]
**Is your feature request related to a problem? Please describe.**

In a discord conversation it came along that there are competitions between users regarding the count of likes (who has more likes). To ensure mental health, it should be possible to disable the visibility of likes.

**Describe the solution you'd like**
There should be a option in the profile settings to disable the likes entirely, so you are not seeing any likes and of course not being able to like journeys. This also includes the notifications, so you don't get notified.  

**Additional context**

<img width="452" alt="image" src="https://user-images.githubusercontent.com/28200315/229210555-f1e1aa23-e031-4ef3-89b7-3bd260587532.png">

**Comment by jeyemwey** [comment]
Should it be visible to other users that you have set the option? I.e. in that the like button isn't visible on one's statuses?

**Comment by bendix-dev** [comment]
> Should it be visible to other users that you have set the option? I.e. in that the like button isn't visible on one's statuses?

That would certainly help for the mentioned issue. I only fear that could be a little intransparent for other users why the likes aren't available for certain statuses.
