### ISSUE TITLE
Ein Manuelles Einfügen von Fahrten (mit Zwischenhalten) die nicht über die Fahrplan API kommen wäre eine coole Sache. So könnte man auch Sonderfahrten aller Art hinzufügen. Das ganze natürlich ohne Punktewertung.

### ISSUE THREAD

**Issue by srype** [Traewelling/traewelling#1518]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HerrLevin** [comment]
We should also add the possibility to create taxi-checkins.

Maybe we could also add the possibility of adding other means of transport, e.g. bike, car or plane? (Needs discussion)
