### ISSUE TITLE
ICS URL display time is very very short

### ISSUE THREAD

**Issue by jheubuch** [Traewelling/traewelling#1547]
**Describe the bug**
When I create an ICS token to export my journeys to a calendar, the URL for export is displayed just in a very short time and not very readable.

**To Reproduce**
Create ICS token url

**Expected behavior**
The URL is displayed clearly for a longer time (or until I dismiss it) so that I have enough time to copy it. Alternatively I'd be fine with being able to copy the URL at any time from the integration list

**Screenshots**
![image](https://user-images.githubusercontent.com/60344409/234223344-24cd7d97-9320-4c77-88fe-dda6c2ea1fae.png)

**Comment by MrKrisKrisu** [comment]
@HerrLevin Can we revert this?
https://github.com/Traewelling/traewelling/commit/14fa5f0e8137899254b0abe75066dbc32cebe95a
