### ISSUE TITLE
Falsche Berechnung Kilometer

### ISSUE THREAD

**Issue by chaoscaptain99** [Traewelling/traewelling#1562]
**Describe the bug**
Seit Samstag: Nach dem Check-In in eine Frankfurter U-Bahn wird die zurückgelegte Strecke teilweise sofort, teilweise erst bei Neu-Laden der Seite falsch berechnet, zum Teil um ein Vielfaches (7 km statt 700 m). Nach mehrfachem Test scheint die gewählte Verbindung und Uhrzeit/ Tag keine Auswirkungen zu haben. Auch in der Kartenansicht werden extreme Umwege angezeigt. 

Gewähltes Gerät und Browser beeinflussen den Fehler nicht. Getestet mit macOS 13/ Windows 10/ iOS 16.4 mit safari und Edge.

**Expected behavior**
Korrekte Berechnung der Fahrtstrecke und Anzeigendes Linienweges ohne extreme real nicht vorhandene Umwege. Am Freitag hat es noch wie erwartet funktioniert.

**Screenshots**

![IMG_6272](https://user-images.githubusercontent.com/132295683/235504863-d8cd36a7-cf49-41d9-828a-2fc71ccde6bf.jpeg)

![IMG_6273](https://user-images.githubusercontent.com/132295683/235504889-f7869d78-6dde-483e-9ee1-dd4eaca17158.jpeg)

**Comment by dasBunny** [comment]
The issue here is that before saturday only the direct path between stations, without considering any curves of the track, was used for anything but trains in Germany. Now Träwelling will calculate the shortest path on rails between the piece of track closest to the location point of the start and destination station respectively.
Sometimes, as is the case with Willy-Brandt-Platz in Frankfurt, there are multiple tracks of different lines, which are not connected at that station. In your case it has incorrectly started your track at the overground stop infront of Frankfurt Hbf, but correctly assumed that you will arrive at the tunnel at Willy-Brandt-Platz. It therefore looks for the quickest way to go from the overground line into the tunnel, which causes the detour.

I have experienced a similar issue today. I was travelling to St. Gallen on the standard gauge network, but the destination location was put on the narrow gauge track at the station, leading to the route taking a massive detour through Wil, where the routing thinks switching between standard and narrow gauge is possible, then all the way back through the narrow gauge network. This seems to be a general problem everywhere where different locally unconnected networks share the station.

**Comment by michael-mezgo** [comment]
Diese Umwege treten leider seit dem Release 1.33 auf. Seit dem werden die Routen, welche HAFAS nicht liefert mit Brouter berechnet (anstatt nur die Luftlinie berechnet). PR #1545

Grundsätzlich freue ich mich über diese Änderung, jedoch habe ich in meinem Umfeld auch schon viele Umwege gesehen.

Beispiele:
- Wien Meidling: Die Züge der Pottendorfer Linie können nur Bahnsteige 7/8 bzw. den hinteren Teil von Bahnsteig 6 bedienen. (Wenn man nun in einen solchen Zug eincheckt, wird ein Umweg über das Vorfeld des Bahnhofs gemacht, welcher sich allerdings in Grenzen hält.) / Beispiel: S60 Wien Blumental ➡️ Wien HBF
![image](https://user-images.githubusercontent.com/58122000/235730522-9298c7c4-a29f-43bd-960e-d892a5b26fa2.jpeg)
- Wien Stephansplatz: Hier funktioniert die Route der U1 leider nicht gut. Es wird ein Umweg durch halb Wien gemacht. / Beispiel: U1 Wien Schwedenplatz ➡️ Wien Karlsplatz
![image](https://user-images.githubusercontent.com/58122000/235731018-ca4fd855-f61b-462f-9b8c-48d3bf6cfeb0.jpeg)
![image](https://user-images.githubusercontent.com/58122000/235730584-efab838c-2bcb-4112-9041-e93209e8c5c5.jpeg)
![image](https://user-images.githubusercontent.com/58122000/235730621-db593e69-eccf-44b5-9c89-22b70cb12977.jpeg)
- Wien Reumannplatz (U1): Hier gibt es besonders viele Probleme. Aus der Route der Stationen vor und nach dem Reumannplatz **(ca. 2 km) werden 48 km**. / Beispiel: U1 Wien Keplerplatz ➡️ Wien Troststraße
![image](https://user-images.githubusercontent.com/58122000/235730758-a68d300e-ba3e-4b96-9ae5-409716320312.jpeg)
![image](https://user-images.githubusercontent.com/58122000/235730778-18109f84-95ed-4371-8bc0-838c1c218a9d.jpeg)

Wäre es möglich, dass man bei Checkins vorerst zwischen Luftlinie und berechnetem Weg entscheiden kann? Denn derzeit sind die berechneten Daten an manchen Stellen leider nicht zu gebrauchen.

**Comment by HerrLevin** [comment]
> Grundsätzlich freue ich mich über diese Änderung, jedoch habe ich in meinem Umfeld auch schon viele Umwege gesehen.
Das Problem liegt wohl daran, dass wir vom HAFAS grobe Punkte zur Positionsbestimmung bekommen, die mal mehr und mal weniger akkurat sind. Bei manchen Straßenbahnhaltestellen liegt die Koordinate dann neben dem Straßenbahngleis, also kann brouter die nächstbeste Route zum nächstbesten Gleis finden. Das Passt also doch ganz okay.


Das Problem scheint wohl an folgendem zu liegen:
Bei Zügen ist das Problem, dass bei einem Bahnhof mit X Gleisen die Koordinate ein Glücksgriff ist. Je nachdem könnte so ein hypothetischer Bahnhof Gleis 1-2 ausschließlich für Regionalzüge haben und 3-4 ausschließlich für Fernverkehr, ohne eine Möglichkeit, in Bahnhofsnähe die Gleise zu wechseln. Brouter weiß nicht, dass wir "nur grob in der Nähe" gerne ein Gleis hätten, sondern sucht genau auf die Koordinate. Jetzt liegt diese auf Gleis 4, dabei sind wir ein Regionalzug, der auf 1 ankommen möchte. Es kann also sein, dass am Bahnhof zuvor die Koordinate auf dem Regionalgleis liegt, im Bahnhof danach auf dem Fernverkehrsgleis und brouter routet dann durch den Bahnhof durch und 5km später wieder in den Bahnhof rein. 

**Falls irgendwer weiß, wie man in brouter einen Ziel_radius_ eingeben kann, bitte meldet euch!** 🥺 

Mein vorläufiger Ansatz wäre jetzt, nach einer prozentualen Abweichung zu suchen und dann entsprechend den Neurouting-Prozess zu unterbinden. Das wäre zumindest am einfachen umzusetzen. Falls das nicht klappt, würde ich ÖPNV vorerst aus dem Feature entfernen, bis wir eine richtige Lösung haben. Die Möglichkeit, die Luftlinie statt des berechneten Weges zu nutzen wäre tatsächlich etwas komplexer. 

Sobald wir eine Lösung haben, werden wir auf jeden Fall alle fehlerhaften Strecken neu berechnen bzw. ein Feature zur Neuberechnung anbieten.

**Comment by MrKrisKrisu** [comment]
> Falls das nicht klappt, würde ich ÖPNV vorerst aus dem Feature entfernen, bis wir eine richtige Lösung haben.

Ggfs. wäre auch eine temporäre Idee, dass man das Feature erstmal "on demand" bereitstellt. Per Default nehmen wir die via HAFAS bereitgestellten Daten, bieten aber einen Knopf zum "Route generieren" an. Dann kann ein User für sich selbst entscheiden, ob er z.B. für Auslandsfahrten wo die Strecke fehlt mehr Daten möchte. Wäre natürlich Aufwand, aber ggfs. für einen Worst Case. 🫣

**Comment by HerrLevin** [comment]
Ein Fix wäre mit #1566 möglich. Damit können wir auch direkt kaputte Status aufräumen. Da muss aber ein anderer aus dem Team nochmal drüber schauen und das morgen evtl. durchführen. Die automatische Neuberechnung für alles was <= S-Bahn ist wurde kurzerhand ausgeschaltet, dass nicht noch mehr Schäden entstehen.

**Comment by MrKrisKrisu** [comment]
Das Issue hier ist meiner Meinung nach jetzt erledigt. Mit #1566 wurde ein Workaround ausgerollt. Nicht perfekt, aber löst zumindest erstmal dieses Problem grob. Nächster Schritt wäre mal zu schauen, wie wir das System mit Brouter optimieren können, aber das wäre ein anderes Issue: #closed
