### ISSUE TITLE
Exported CSV files missformated

### ISSUE THREAD

**Issue by SpielenmitLili** [Traewelling/traewelling#1563]
**Describe the bug**
When exporting as CSV file, if the status that can be entered goes over multiple lines, it will be output in multiple lines in the CSV file. This causes problems with imports, if you try to read the data with common CSV readers, because they are line-based.

**To Reproduce**

1. Go to ''https://traewelling.de/export"
2. Click on 'Export as: CSV'
3. Open file with Notepad ++ or Notepad

**Expected behavior**
If the status in the export would go over several lines, it should be separated with a separator like \n

**Screenshots**
![image](https://user-images.githubusercontent.com/74246564/235616884-f47dc1b6-b3cb-4ade-ac63-066e2bcc7d4e.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Enterprise LTSC
- Browser Google Chrome
- Version 112.0.5615.138

**Comment by MrKrisKrisu** [comment]
In my test, the status body is escaped correctly, so it results in a valid CSV. Do you have more information what is the error in your case? In a CSV new rows can be displayed as long as it is escaped correctly.

![image](https://user-images.githubusercontent.com/4103693/236549642-1f7510f4-c89a-49f3-9b2c-ac9db8fc87ba.png)

**Comment by MrKrisKrisu** [comment]
Since here no more answer came and it works for me I close this issu enow. Let me know if this is still occuring.
