### ISSUE TITLE
Fehlerhafte Längenangaben bei Münchner U-Bahnfahrten

### ISSUE THREAD

**Issue by Kuestenkind86** [Traewelling/traewelling#1567]
**Describe the bug**
Bei Fahrten mit der U2 (z.B. von München Hbf zum Josephsplatz oder vom Josephsplatz nach Feldmoching) werden falsche Längenangaben verwendet.

**To Reproduce**

Fahrt auswählen:
München Hbf --> München Josephsplatz (Fahrtrichtung Feldmoching): wird mit 31 km angegeben, Gegenrichtung korrekt mit 2 km.
München Josephsplatz --> München Feldmoching wird mit 70 km angegeben, Gegenrichtung korrekt mit 9 km.
In Kartendarstellung werden auch deutliche Umwegfahrten im Stadtgebiet angezeigt - vermutlich ein Fehler in den "angezapften" Fahrplandaten

**Expected behavior**

**Screenshots**

![grafik](https://user-images.githubusercontent.com/132501108/236026905-69348585-9ec9-4c27-9fd2-a6532aa7ad69.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MrKrisKrisu** [comment]
Hi! Danke für das Anlegen des Issues.
Der Fehler sollte mit dem Workaround aus #1566 prinzipiell gelöst sein.
