### ISSUE TITLE
Paris RER is missing stops/data

### ISSUE THREAD

**Issue by rugk** [Traewelling/traewelling#1572]
**Describe the bug**
Okay the metro of Paris is not included in traewelling, that is acceptable. However, the RER train (which runs underway and through metro stations too, but is AFAIK classified as a train), is included. However, only partially?

**To Reproduce**
I use Transportr 2.1.4 to plan my trips. (All data from today.)

E.g. there is this trip:
12:37 Massy - Verrières
  🚈 B → Aéroport Charles De Gaulle 2 (terminal 2) (tremblay-en-france)
13:11 Gare Du Nord

13:11 Gare Du Nord
  🚶 Fußweg 296 m für 2 min
13:13 Gare Du Nord

13:17 Gare Du Nord
  🚇 5 → Bobigny Pablo Picasso (bobigny)
13:22 Laumière

(Achtung: Zeiten können gemeldete Verspätungen enthalten)

Erstellt von Transportr
https://transportr.app/?utm_source=shared_trip

---

That the metro is not included is okay, but neither the start norstop stations can be found in Traewelling.

https://traewelling.de/status/990821

If not viewable anymore, this is the trip:
> Antony Ratp 12:50
>
> suburban RER98065 13km 20min
>
> Missing stations again: from Massy - Verrières to Gare Du Nord
> #interrail #interrailing #interrail2023
> 13:10 Paris Chatelet/Les Halles 

**Current behaviour**
As you can see the train is in traewelling the correct one. (The stop at antony was at the correct time) However, some train stops are missing (compared to Traewelling):

![IMG_20230506_125505](https://user-images.githubusercontent.com/11966684/236620039-562fdccd-b400-41a6-ac3e-e72120fc3950.jpg)

![Screenshot_20230506-125617](https://user-images.githubusercontent.com/11966684/236620085-06ae2c7d-1d4a-4e20-ab17-67aee408b287.png)

**Edit:** just see Transportr is slightly off by the time of Antony, but the train was actually there like :50. I don't know if that is delay or the time is just off, but yeah, having the time correct is also rather not such a big problem compared to missing stops.

**Expected behavior**
At least the stops included in Transporter should be included.

**Screenshots**
Ssee above

**Desktop (please complete the following information):**

- OS: [e.g. iOS

**Smartphone (please complete the following information):**

Device: Fairphone 4 (FP4)  
OS: Android 13, CalyxOS 4.9.0  
Build-ID: `TQ2A.230505.002.23409000` 
Firefox for Android 112

**Additional context**
* I noticed some stops like "Massy - Verrières' are often missing from Transportr too for this RER (RER B). (But the station also once showed that stop as missing and it stopped yhere, i have no idea.) However, I chose this example, where everything is valid in Transportr, which IMHO should also be in Traewelling then.
* the Paris metro system is complicated, so I choose this simple example

**Comment by vainamov** [comment]
To query stations and services, Traewelling uses [DB REST](https://v6.db.transport.rest/) which in-turn uses the HAFAS API from Deutsche Bahn. It's therefore limited to whatever data the Deutsche Bahn provides. Foreign connections are known to be missing or faulty.

**Comment by rugk** [comment]
Hmm I see. Are there any plans/is there an issue already for maybe using https://github.com/schildbach/public-transport-enabler/ or so (the same library Transportr uses) to enable support for more regions?
See https://transportr.app/contribute/ for more details.

**Comment by HerrLevin** [comment]
We want to include multiple data providers in the future but currently we have our focus on completing the client-API and fixing multiple Bugs. Implementing multiple data providers is (probably) a bigger thing on our plates, that's why we currently cannot tell, when we'll be able to do that. (But we want to make that change as soon as we're able to)

**Comment by MrKrisKrisu** [comment]
As this is an issue about missing data sources, I'll close this issue and refer to this one to collect all of these: #1635
