### ISSUE TITLE
Cannot enable likes

### ISSUE THREAD

**Issue by vainamov** [Traewelling/traewelling#1609]
**Describe the bug**
When trying to update the privacy settings to enable likes, the server throws an internal server error.

**To Reproduce**

1. Go to Settings
2. Enable '"Gefällt mir"-Angaben anzeigen'
3. Submit

**Expected behavior**
It shouldn't fail.

**Desktop (please complete the following information):**

- OS: macOS Monterey 12.6.5
- Browser: Firefox
- Version: 112.0.2

**Additional context**
Request body:
```
_token=[redacted]
prevent_index=0
default_status_visibility=0
privacy_hide_days=
mastodon_visibility=1
likes_enabled=on
```

**Comment by MrKrisKrisu** [comment]
I cannot reproduce this. Can you please try again? Maybe you tried it while @HerrLevin was updating.

**Comment by vainamov** [comment]
![grafik](https://github.com/Traewelling/traewelling/assets/11841072/906807f2-acf0-4c74-a73e-0f8c768907d4)

In the meantime, it seems to have worked without me having to try it again.
