### ISSUE TITLE
Sporadic error messages about missing fields

### ISSUE THREAD

**Issue by rugk** [Traewelling/traewelling#1618]
**Describe the bug**
Whne I click on "Mitfahren" ("ride along") (I guess this may be more often like this.) and enter my data sometimes I get strange errors about missing fields.
Just retrying usually fixes that.

I use Traewelling as a PWA in Firefox for Android.

**To Reproduce**
1. Traewel with another person.
2. I activate mastodon posting and the list button, which I don't quite get what it does but maybe something with ranking.
3. Click submit.

This error is shown:
![IMG_20230525_132442](https://github.com/Traewelling/traewelling/assets/11966684/2489e13d-029d-48f1-93cd-2452b5584c7e)

**Expected behavior**
No error

**Screenshots**
See above

**Smartphone (please complete the following information):**

Device: Fairphone 4 (FP4)  
OS: Android 13, CalyxOS 4.9.0  
Build-ID: `TQ2A.230505.002.23409000` 
Firefox 113.1.0

**Additional context**
As I am hopping WiFi and mobile networks near trains, my internet connection may be not that reliable. But Traewelling should account for that for obvious reasons…🫠

**Comment by MrKrisKrisu** [comment]
I haven't seen these error messages for a long time.  Please let me know if this is still up to date, I'll close this issue for now.

**Comment by rugk** [comment]
Have recently seen them again in bad network condition cases. Usually it happens when the requests times out or similar things, I suspect.
