### ISSUE TITLE
Add personal access token to apps

### ISSUE THREAD

**Issue by HerrLevin** [Traewelling/traewelling#1637]
**Is your feature request related to a problem? Please describe.**
As an end user trying to test out the API for myself, I don't want to go through the hassle of the OAuth-process.

**Describe the solution you'd like**
We should add a UI option to add/(re)generate a personal access token just like Mastodon or twitter

**Additional context**
This might encourage users to not use user/pass authentication, since this option will be removed in the future.
Example from mastodon:
![image](https://github.com/Traewelling/traewelling/assets/1267894/867a5055-12a7-4796-9ac0-4575b7589741)

**Comment by jeyemwey** [comment]
When implemented, we could use this method to simplify the calendar link feature.
