### ISSUE TITLE
Incorrect Bus Stop in Route - Wrong Kilometer Count and Too Many Points Given

### ISSUE THREAD

**Issue by ErikUden** [Traewelling/traewelling#1647]
**Describe the bug**
https://traewelling.de/status/1091464
The bus ride from **Rauenhahn, Asbach (Westerwald)** to **Himberg, Bad Honnef**, using the **SB51** bus, the route believes one of the bus' stops to be in the wrong location, and hence displays an incorrect map, distance traveled, and attributes too many points. 
![Screenshot_20230606_164546_Trwelldroid.jpg](https://github.com/Traewelling/traewelling/assets/52011431/00b0e28a-b9a7-467b-8123-c9944f87bb0f)  

**To Reproduce**
1. Under “Where are you?” enter and select Rauenhahn, Asbach (Westerwald) 
2. Search for the **Bus SB51** into the direction of **Bad Honnef (Stadtbahn)** (*every week day at HH:46*), or try the specific time of 11:46 AM on the 7th of June 2023
3. Select the bus
4. Select “Himberg, Bad Honnef” as your destination
5. Map and kilometer count should be as shown

**Expected behavior**
The correct route and kilometer count should be displayed. 

**Screenshots**
![Screenshot_20230606_164546_Trwelldroid.jpg](https://github.com/Traewelling/traewelling/assets/52011431/00b0e28a-b9a7-467b-8123-c9944f87bb0f)  

**Smartphone (please complete the following information):**

- Device: Samsung S10
- OS: One UI 4.1 / Android 12 (*rooted*) 
- Browser: Firefox / Träwelldroid 
- Version: v1.13.1 (89) (*F-Droid*) 

**Additional context**
N/A

**Comment by MrKrisKrisu** [comment]
Unfortunately, there is nothing we can do here, as the polyline is transmitted by HAFAS in this way. Ideally, you would have to contact the transport association that provides the data.

(From my own experience, however, nothing will happen if you report this. That's why ICEs still regularly travel over non-electrified routes according to Polyline).
