### ISSUE TITLE
Active journeys not loading

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/traewelling#1674]
**Describe the bug**
Since the Vue update (#1665) the Active Journeys map isn't loading because the JS-Class is not defined.

**Screenshots**
![image](https://github.com/Traewelling/traewelling/assets/4103693/8ff364cd-05f6-4dfe-b989-881f72fc5b12)

**Additional Context**
https://traewelling.de/statuses/active

**Comment by HerrLevin** [comment]
My (hopefully) easy fix would be, to move the include of app.js inside the app.blade.php from the footer to he head and also only start vue.js once the dom document is fully loaded.
