### ISSUE TITLE
Notifications icon doesn't change color if notifications are shown

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/traewelling#1675]
**Describe the bug**
Before the Vue-Update (#1665) the bell's background was colored white if notifications are available. As of the update this is missing and affects user experience.

**Screenshots**
![image](https://github.com/Traewelling/traewelling/assets/4103693/2784fc6e-4157-4550-a44a-8ec956077c46)

**Aditional Context**
Icon class should be just replaced.
`icon.classList.replace("far", "fa");`

**Comment by HerrLevin** [comment]
My (hopefully) easy fix would be, to move the include of app.js inside the app.blade.php from the footer to he head and also only start vue.js once the dom document is fully loaded.
