### ISSUE TITLE
Notification count misplaced on some screen sizes

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/traewelling#1677]
**Describe the bug**
Since the Vue-Update (#1665) the badge with the numbers of notifications isn't placed correctly in some screen wides.
The following screenshot is taken at `811px * 948px`.

**Screenshots**
![image](https://github.com/Traewelling/traewelling/assets/4103693/c699ad97-3d14-4fd3-9d98-73b91f22b872)

**Comment by HerrLevin** [comment]
Hmpf. I'm too bad for CSS. :(

**Comment by pascalwittler** [comment]
A simple pure-css solution is to add

```css
white-space: nowrap;
```

to the `<button>` element to avoid the line break between the two included `<span>` elements (bell icon + notification count badge)
