### ISSUE TITLE
Cannot check-in if there are no stations, also not to last/end station

### ISSUE THREAD

**Issue by rugk** [Traewelling/traewelling#1693]
**Describe the bug**
When checking in from Wigan North Western to  Liverpool Lime Street (a Great Britian "Northern line" train), you cannot check-in, because:
* no stations are listed
* but you also cannot check-in to the last station via that dedicated button unfortunately, which I don't get why that does not work 

**To Reproduce**

1. Go to https://traewelling.de/trains/stationboard?provider=train&ibnr=7002411&when=2023-06-25T17%3A18%3A11%2B02%3A00 and check-in in 17:23 – in UTC+02, but [that is another topic](https://github.com/Traewelling/traewelling/issues/1692)):
   ![grafik](https://github.com/Traewelling/traewelling/assets/11966684/c8c93a65-c99d-4bc8-ae05-e210a62a056d)
2. So there are no stations [on the next page](https://traewelling.de/trains/trip?tripID=1%7C155208%7C4%7C80%7C25062023&lineName=59450&start=7002411&departure=2023-06-25T17%3A23%3A00%2B01%3A00):
   ![grafik](https://github.com/Traewelling/traewelling/assets/11966684/a81047e0-4ecf-4a95-8851-2c06d57d1668)
3. Click on that special button at the top right that I expect may be made for this purpose or in general when for going to the last station:
   ![grafik](https://github.com/Traewelling/traewelling/assets/11966684/328156bc-fa8c-47a5-abcc-91606929db61)
4. You get an error:
   ![grafik](https://github.com/Traewelling/traewelling/assets/11966684/3c707565-caa0-4313-bd67-d3808e2fa964)

**Expected behavior**
Should check-in to last station, I mean it has the correct name, should not that be possible?

**Screenshots**
network traffic causing error:
![grafik](https://github.com/Traewelling/traewelling/assets/11966684/a2c22acd-b9ca-4a98-8721-4aa6bea98c3b)

**Desktop (please complete the following information):**
- OS: Linux/Fedora
- Browser: Firefox 
- Version: 114

**Smartphone (please complete the following information):**
(also reproduced)

**Additional context**
N/A

**Comment by MrKrisKrisu** [comment]
belongs also to #1511 due to timezone problems

**Comment by HerrLevin** [comment]
@rugk Okay, I just found out that you can in fact complete a checkin, if you remove the Timezone in the URL.
That way https://traewelling.de/trains/trip?tripID=1%7C155208%7C4%7C80%7C25062023&lineName=59450&start=7002411&departure=2023-06-25T17%3A23%3A00%2B01%3A00 becomes https://traewelling.de/trains/trip?tripID=1|155208|4|80|25062023&lineName=59450&start=7002411&departure=2023-06-25T17%3A23 and you'll see the stations. 

I'll try to figure out a hotfix for that.
