### ISSUE TITLE
Translate Träwelling to Swedish

### ISSUE THREAD

**Issue by jeyemwey** [Traewelling/traewelling#17]
@DC7IA offered to translate Träwelling to Swedish. He said, it will take some time, but he will do it.

**Comment by DC7IA** [comment]
Yes. But might take a lot of time. :)

**Comment by DC7IA** [comment]
Done translating. Now waiting for feedback from friends, maybe this weekend already. :)

**Comment by rugk** [comment]
:upside_down_face: 

I don't see whether you use a translation platform or so (might be a good idea though), as I could not find it linked anywhere, but well… this issue might need some attention. :blush:

**Comment by jeyemwey** [comment]
We have merged the language files, but have not added the links yet.

I'm not sure if using more tooling would be overkill for this project. We do not plan to support more languages right now.

**Comment by DC7IA** [comment]
I'd like to use Weblate. Looks like you only upload the files and random strangers will start contributing. :D

Maybe use the weblate instance usageDirect uses as well?

**Comment by DC7IA** [comment]
Weblate notifies if I need to act and makes the whole process MUCH easier to do.

**Comment by HerrLevin** [comment]
That sounds very good. Currently, I don't have the time setting up this service but I'll be looking into it as soon as possible.

**Comment by DC7IA** [comment]
Might even add Danish then, I can do more since it will be a lot less work. :)

**Comment by HerrLevin** [comment]
Okay, I've set up an instance at https://weblate.bubu1.eu/projects/trawelling/. I still have to configure a few things but for now I hope it's working. :D

**Comment by HerrLevin** [comment]
(I've also set up a testing-instance at https://poeditor.com/projects/view?id=432915 – not sure if this is the better solution.)

**Comment by MrKrisKrisu** [comment]
Since we are now outsourcing the translations to Weblate and I don't see any reason to have the open ticket here, I would close this once.

Translations please from now on here: https://weblate.bubu1.eu/projects/trawelling/common/sv/

**Comment by DC7IA** [comment]
> Since we are now outsourcing the translations to Weblate and I don't see any reason to have the open ticket here, I would close this once.
> 
> Translations please from now on here: https://weblate.bubu1.eu/projects/trawelling/common/sv/

Yay, much easier then editing files in git by hand. :D
