### ISSUE TITLE
Dark mode: Notifications are light

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/traewelling#1711]
**Describe the bug**
Notifications doesn't have a dark mode

**Screenshots**
![image](https://github.com/Traewelling/traewelling/assets/4103693/b8839821-e371-4e02-974f-a348926839d5)

**Comment by MrKrisKrisu** [comment]
(Additional hint: Notifications are written in Vue if this is useful while fixing this)

/cc @thilobillerbeck

**Comment by thilobillerbeck** [comment]
Apparently this was the issue, since the Vue component brought its own styling which has overriden mine. Should be fixed by linked PR.
