### ISSUE TITLE
Dark Mode: Page Number Navigation not fully adapted to dark mode

### ISSUE THREAD

**Issue by thilobillerbeck** [Traewelling/traewelling#1715]
**Describe the bug**
Some parts of the page number navigation don't adapt to the dark theme

**Screenshots**
![Screenshot_20230706-030939.png](https://github.com/Traewelling/traewelling/assets/7442383/c949fd3a-2c6b-4e91-8b1a-198b12d6b7bc)

**Comment by MrKrisKrisu** [comment]
may be a duplicate of #1709?

**Comment by thilobillerbeck** [comment]
![image](https://github.com/Traewelling/traewelling/assets/7442383/2def7990-856d-433f-8e94-286b625329a6)

shadows look a bit ugly imo. but this qualifies as usable imo. propably close that for now
