### ISSUE TITLE
Cannot check in some UK trains

### ISSUE THREAD

**Issue by timoschwarzer** [Traewelling/traewelling#1718]
**Describe the bug**
I tried to check in to this train: https://traewelling.de/trains/trip?tripID=1%7C156441%7C0%7C80%7C7072023&lineName=59347&start=7000431&departure=2023-07-07T21%3A00%3A00%2B01%3A00 resulting in an error message ("An unknown error occurred. Please try again.")

**To Reproduce**

1. Click link above
2. Select "Peterborough"

**Desktop (please complete the following information):**

- OS: Linux
- Browser Chrome
- Version 114

**Comment by HerrLevin** [comment]
This should be fixed with https://github.com/Traewelling/traewelling/pull/1719 and rolled out on prod
