### ISSUE TITLE
Notifications not working on mobile view

### ISSUE THREAD

**Issue by jheubuch** [Traewelling/traewelling#173]
**Describe the bug**
When I open the "notifications" panel on my mobile, they won't be displayed. On my desktop, they are being displayed without any problems.

**To Reproduce**
1. Trigger a notification
2. Go to notifications panel on mobile --> no notifications
3. Go to notifications panel on desktop --> notifications are displayed 

**Expected behavior**
Notifications are also displayed on mobile view

**Screenshots:**
![image](https://user-images.githubusercontent.com/60344409/105824750-0f98da80-5fbf-11eb-9c08-123cd3ad071f.png)
![image](https://user-images.githubusercontent.com/60344409/105824964-54247600-5fbf-11eb-8cea-bc1bb6f3a0fd.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version 88.0.705.50

**Smartphone:**
 - Device: Google Pixel 4 XL
 - OS: Android 11
 - Browser: Chrome
 - Version: 88.0.4324.93

**Additional context**
-

**Comment by MrKrisKrisu** [comment]
I can confirm this issue on my Android Device, too. It seems that the click-event is not handled correctly within the JavaScript Code.

**Comment by MrKrisKrisu** [comment]
Thanks for the report. The fix will be rolled out soon, but it can be delayed because we are currently in a server-migration.
