### ISSUE TITLE
"sessions" table does not exist in Dev setup

### ISSUE THREAD

**Issue by pReya** [Traewelling/traewelling#1753]
**Describe the bug**
Tried setting up the Dev environment according to the readme via Docker compose. Seeded the database and started the docker setup. When I access the web interface via port 8081, I get an error about the missing `sessions` table:

SQLSTATE[HY000]: General error: 1 no such table: sessions 

Did I do something wrong? Is something missing in the docs?
**To Reproduce**

1. Clone project
2. Set `SEED_DB=true`
3. Run the compose file
4. Open localhost:8081 in your browser

**Expected behavior**
Should show the App

**Screenshots**
<img width="1512" alt="Screenshot 2023-07-18 at 22 36 13" src="https://github.com/Traewelling/traewelling/assets/4677417/5cec558d-9e7d-4680-96f9-d9b188671fb6">

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Firefox 
- Version: 116.0

**Comment by MrKrisKrisu** [comment]
Do you overwrite `SESSION_DRIVER` in you env? This should be `database` when seeding.

**Comment by pReya** [comment]
> Do you overwrite `SESSION_DRIVER` in you env? This should be `database` when seeding.

Did not change anything about this value – as there was nothing in the documentation.

Would you mind summarizing the necessary steps to have a seeded database in the dev setup? I'd be happy to add it to the documentation.

**Comment by HerrLevin** [comment]
> Would you mind summarizing the necessary steps to have a seeded database in the dev setup?

Iirc there's only a few steps:
Clone, composer install, npm install, npm run dev

DB-wise you'll have to define your database. Either use sqlite (DB_HOST should point to a .sqlite file) or mysql/maridb.

Once that is set up you'll need the following commands:
- php artisan key:generate
- php artisan migrate:fresh --seed
- php artisan passport:install

**Comment by HerrLevin** [comment]
Ohhhhh. You meant the docker setup. Sorry, i didn't see that the first time.
I haven't used the docker setup until now. Maybe @jeyemwey can help here?

**Comment by jeyemwey** [comment]
The sessions table is usually the first table that is queried on a page request, and that fails when the database isn't available.

The error presented is a MySQL error, so the connection and login seems to work, but the database is empty. Can you try `php artisan migrate` before the db seed command? That should initialize empty tables.

**Comment by pReya** [comment]
> The sessions table is usually the first table that is queried on a page request, and that fails when the database isn't available.
> 
> The error presented is a MySQL error, so the connection and login seems to work, but the database is empty. Can you try `php artisan migrate` before the db seed command? That should initialize empty tables.

So what you're saying is:
1. Run `compose up` without `SEED_DB=true`
2. Run `php artisan migrate`
3. Run `compose up` WITH `SEED_DB=true`

Correct?

**Comment by jeyemwey** [comment]
Yes something like this. The db seed command is just for dummy data, you can skip it as well and just register your own user in the web app.Am 19.07.2023 19:36 schrieb Moritz Stückler ***@***.***>:

The sessions table is usually the first table that is queried on a page request, and that fails when the database isn't available.
The error presented is a MySQL error, so the connection and login seems to work, but the database is empty. Can you try php artisan migrate before the db seed command? That should initialize empty tables.

So what you're saying is:
Run compose up without SEED_DB=trueRun php artisan migrateRun compose up WITH SEED_DB=true
Correct?

**Comment by MrKrisKrisu** [comment]
Please retry with the changes from #2074 and reopen if the error still exist for you.
If you don't overwrite `SESSION_DRIVER` in your environment the table should be created.
