### ISSUE TITLE
Not enough colors in the personal statistics

### ISSUE THREAD

**Issue by FunkoLive** [Traewelling/traewelling#1768]
**Describe the bug**

In the travel statistics it is not possible to see all transport companys in a different color. There are often two with the same color, which makes the statistics useless if the mouse isn't on the circle.

**To Reproduce**

1. Go to 'Personal statistics'
2. Scroll down to 'Transport companies'
3. See error

**Expected behavior**

A separate color for every transport company

**Screenshots**
![grafik](https://github.com/Traewelling/traewelling/assets/77592176/f9a47b37-a9cd-4b95-b17f-73da14e0fc1e)

**Comment by MrKrisKrisu** [comment]
This issue already exists under #1245.
I would like to discuss it further there. Would be happy if you also have color suggestions.
