### ISSUE TITLE
Check-in for travels across Great Britains give an unexpected error

### ISSUE THREAD

**Issue by saschazepter** [Traewelling/traewelling#1770]
**Describe the bug**

Check-in for travels across Great Britains give an unexpected error.

**To Reproduce**

1. Go to 'Dashboard'
2. Enter 'Luton Airport Parkway' for the station
3. Use the datetime picker to enter '07/21/2023 11:16 pm' as the date and time
4. Select the train 69684 at 11:16 pm for check-in
5. Choose 'London St. Pancras' for the stop

**Expected behavior**
A successful check-in for the selected travel should happen.

**Screenshots**

**Desktop (please complete the following information):**
Happens on all clients and browsers.

**Smartphone (please complete the following information):**
Happens on all clients and browsers

**Additional context**

**Comment by MrKrisKrisu** [comment]
@HerrLevin is this also fixed with #1719?

**Comment by HerrLevin** [comment]
@MrKrisKrisu need to check it first before I can make a definitive answer but could be very likely

**Comment by HerrLevin** [comment]
This is fixed with #1719 and rolled out on prod
