### ISSUE TITLE
Fix ui of application settings

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/traewelling#1773]
**Describe the bug**
I don't know what happened there, but the layout of the developer settings are somewhat broken.

**To Reproduce**
https://traewelling.de/settings/applications

**Expected behavior**
Should look beautiful ✨

**Screenshots**
![image](https://github.com/Traewelling/traewelling/assets/4103693/191a16c1-4c13-496c-894d-b6055c1022d1)

**Comment by thilobillerbeck** [comment]
I guess it makes most sense to integrate this page with the rest of the existing design to keep everything consistent and use familiar UI elements. Maybe I can spare some time throughout the next week to put this properly into the existing layout.

**Comment by thilobillerbeck** [comment]
I wonder if we should even integrate a navigation option to reach this page, though thinking about a huge part of the community being not that affine with technology and development work, this might cause confusion.

**Comment by HerrLevin** [comment]
One big misunderstanding here: The "application settings" were supposed to become the new general settings design, but at some point in time it just broke. They weren't supposed to permanently be a separate page. 

I started work on an approach to recreate the settings in a mastodon-like layout (topics in a [collapsible] sidebar for a better structure) but didn't find the time to complete it. It's located in https://github.com/traewelling/traewelling/tree/dev-lb-new-settings
