### ISSUE TITLE
Duration not calculated correctly

### ISSUE THREAD

**Issue by HerrLevin** [Traewelling/traewelling#1779]
**Describe the bug**
Users experienced a decrease in their total travel time.
Some users report a decrease from 1000 to 100 hours.

**To Reproduce**
Migrate from v1.41.x to 1.42

**Expected behavior**
Correct time calculation

**Additional context**
https://twitter.com/nefau1/status/1685573553616281600
https://twitter.com/fel1xham/status/1685571535518519296

**Comment by MrKrisKrisu** [comment]
Oups, I forgot to recalculate the distance because of the last changes to it's calculation. Will do this today!

**Comment by MrKrisKrisu** [comment]
The associated PR fixes that the data is persisted correctly. I still have to recalculate it though. This will take a few more hours until the data is correct.
