### ISSUE TITLE
Times in checkin edit modal are off

### ISSUE THREAD

**Issue by sinsa92** [Traewelling/traewelling#1782]
**Describe the bug**
Let's say you have an existing check in. The train departs a bit delayed, so you add the manual departure time (e.g. 12:00 entered time). Later, the train arrives a bit early and you again add manual times(e.g. 12:59). However, the previously manually added departure time now shows 10:00 in the modal, and if you overlook it and submit it anyway, it would show you the journey lasted from 10:00-12:59.
In addition, the dropdown also had all times off by 2 hours.

**Expected behaviour**
The times should not change without user input, and should stay consistent with timetable data.

**Screenshots**
Screenshot of me opening the edit check in modal without changing any values before taking the screenshot (see check in below the modal):
<img width="1080" alt="image" src="https://github.com/Traewelling/traewelling/assets/36137659/5efee908-d5ab-4389-ad59-e07415718226">

**Smartphone (please complete the following information):**

- Device: iPhone 6+, iPad 2nd Gen
- OS: latest
- Browser: Safari
- Version: latest

**Comment by HerrLevin** [comment]
Thanks for creating the issue. Was about to create the same one. :D

**Comment by sinsa92** [comment]
Another discovery: the stops-dropdown contains every stop twice: once with the 2 hour offset, once without. If you select the stop without the offset, your distance gets cut to 0m and the map just shows one station. The planned arrival is then 2 hours off.

**Comment by HerrLevin** [comment]
@sinsa92 Yep, we're aware of that. It __should__ be fixed with the current release.

**Comment by HerrLevin** [comment]
Fixed in #1784
