### ISSUE TITLE
Fehlende Daten von Trentino Südtirol / Missing Data from Trentino South Tyrol

### ISSUE THREAD

**Issue by mxritzdev** [Traewelling/traewelling#1793]
Gibt es eine Möglichkeit, die öffentlichen Verkehrsmittel von Trentino Südtirol in die Seite einzufügen und wenn ja, kann ich da helfen?

Is there a way to add Trentino Alto Adige public transport to the site and if so, can I help?

**Comment by mxritzdev** [comment]
Viele Bus- und Zugetrecken fehlen.

**Comment by HerrLevin** [comment]
Leider gibt es dafür derzeit keine Möglichkeit. Wir haben #1635 als offene Diskussion dafür, aber derzeit sind wir auf die Daten des DB Navigator beschränkt.
