### ISSUE TITLE
Austrian private high speed rail provider WESTbahn is classified as a regional train instead of an express train

### ISSUE THREAD

**Issue by mdartmann** [Traewelling/traewelling#1794]
**Describe the bug**
When checking into a WESTbahn train, it gets counted as a regional express journey instead of the high-speed/long-distance journey that it is. 

**To Reproduce**

1. Check into any WESTbahn train.
2. Check your statistics to see the journey counts towards a regional express journey.

**Expected behavior**
The WESTbahn journey should be counted towards the express train statistic (probably equivalent to IC/EC trains if not ICE/RJX) 

**Additional context**
WESTbahn is running high-speed trips all across Austria and competes with the national rail operator ÖBB on the Vienna -> Linz -> Salzburg -> Munich/Innsbruck corridor, directly challenging the RJX connections that ÖBB offers. It runs at up to 200 km/h and uses Stadler KISS 3 EMUs with interiors designed for long-distance journeys. 
Considering the fare categories, high speeds and long distances (crossing multiple Austrian state and even country borders) these trains run, they should not be counted as regional express journeys. 

If I can help implement this myself, feel free to point me in the right direction. Thank you so much for your incredible work on this project!

**Comment by MrKrisKrisu** [comment]
Hi! Thanks for creating this issue.

We use [db-rest](https://github.com/derhuerst/db-rest) as a data source, which provides data from Deutsche Bahn's HAFAS. Therefore, unfortunately, we cannot directly change anything in the given data.

**Comment by ET430-Rosenheim** [comment]
Hallo
Actually the Westbahn is classified as an InterRegio (the old IR that's Fernverkehr, not the IRE as in bwegt) in Hafas (at least in DB-Navigator). The WB has a white Twindexx on brey background, while the IRE is black on grey as in normal RE. So it does make sense to flag the issue, after all, this IR is not the IRE.
![Screenshot_20230803-184920](https://github.com/Traewelling/traewelling/assets/92975211/a3f06d16-fee7-42b7-82fe-ca250c18593b)
![Screenshot_20230803-184923](https://github.com/Traewelling/traewelling/assets/92975211/10370a1e-13b6-4d45-a923-f630471e9310)
![Screenshot_20230803-185350](https://github.com/Traewelling/traewelling/assets/92975211/b3bbffaf-c106-4a63-b6e1-00551ffa4b67)
