### ISSUE TITLE
Add website link to GitHub description

### ISSUE THREAD

**Issue by rugk** [Traewelling/traewelling#18]
You can add this to the repo next to the description. :smiley:

**Comment by rugk** [comment]
Ugh sorry, actually I've meant the description on GitHub:
![df](https://user-images.githubusercontent.com/11966684/77254000-7abaa780-6c5e-11ea-8bfc-a442895387ba.png)


I mean the Readme is not bad either, but right at the top could be useful. :smile:

**Comment by jeyemwey** [comment]
Das muss @HerrLevin  machen :D
