### ISSUE TITLE
Clear queue_monitor

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/traewelling#1841]
@jeyemwey You started logging the queue_monitor once. This regularly fills with data without being deleted. 

Is there anything you (or me) can do?
Do we need the logs?
Script for deleting older entries?

**Comment by HerrLevin** [comment]
https://github.com/romanzipp/Laravel-Queue-Monitor#commands States the artisan commands to do this. They just need to be planned correctly.

**Comment by jeyemwey** [comment]
I don't have an overview how many job executions are logged per day, so its a little hard to see how pressing things are.
In an ideal world, I'd like to feed a Grafana board directly with data from this table.
I propose that old data can be deleted safely after a week. I'll create a scheduler to run the clearing every day.
