### ISSUE TITLE
Fehlende Polyline bei Check-in in Frankfurter Straßenbahn

### ISSUE THREAD

**Issue by marhei** [Traewelling/traewelling#1842]
Neuerdings fehlt bei der Frankfurter Straßenbahn die Polyline, dadurch haben alle Fahrten eine Länge von 0m.

<img width="665" alt="Capture d’écran 2023-08-09 à 09 05 26" src="https://github.com/Traewelling/traewelling/assets/10304183/f1e9a39f-91c1-44da-bf20-99a17b9db973">

Beispiele:
https://traewelling.de/status/1303257
https://traewelling.de/status/1302761
https://traewelling.de/status/1305972
https://traewelling.de/status/1307861

Check-Ins wurden über die API (TräwelCheckin) erstellt.

**Comment by marhei** [comment]
Die Polyline scheint erst nachträglich rausgelöscht zu werden, der Check-in hat diese erst nach wenigen Sekunden verloren: https://traewelling.de/status/1308861

Vielleicht Brouter-Integration?

**Comment by MrKrisKrisu** [comment]
To reproduce:

1. Checkin is okay.
![image](https://github.com/Traewelling/traewelling/assets/4103693/ecf05739-5976-40d7-a2aa-b29485846b54)

2. Route is regenerated with Brouter

```
[2023-08-09 14:52:32] local.DEBUG: Dispatching UserCheckedIn event for status#16  
[2023-08-09 14:52:32] local.DEBUG: Missing route found between Preungesheim Gravensteiner Platz, Frankfurt a.M. and Alkmenestraße, Frankfurt a.M.  
[2023-08-09 14:52:32] local.DEBUG: parts missing: dispatch  
[2023-08-09 14:52:33] local.ERROR: TrainCheckin #14: Origin stopover not found. Created a new one.  
[2023-08-09 14:52:38] local.ERROR: TrainCheckin #14: Origin stopover not found. Created a new one.  
[2023-08-09 14:52:39] local.ERROR: TrainCheckin #14: Origin stopover not found. Created a new one.  

```

3. Polyline is gone and distance is 0m

![image](https://github.com/Traewelling/traewelling/assets/4103693/f70f5e9c-c6d6-4bea-a12d-8394b69ccbd9)

**Comment by MrKrisKrisu** [comment]
The GeoJSON after regenerated is a little bit broken...

```json
{
    "type": "FeatureCollection",
    "features": {
        "": {
            "properties": {
                "id": 100912,
                "name": "S\u00fcdbahnhof, Frankfurt a.M.",
                "departure_planned": "2023-08-09T16:52:32.000000Z",
                "arrival_planned": "2023-08-09T16:52:32.000000Z"
            }
        }
    }
}
```

**Comment by HerrLevin** [comment]
FYI: kilometers should be non-zero now. :D
