### ISSUE TITLE
[API] Manually overwritten time cannot be deleted

### ISSUE THREAD

**Issue by jheubuch** [Traewelling/traewelling#1850]
**Describe the bug**
If a time departure/arrival time is manually overwritten, it cannot be reset to null anymore (also when a null-value is sent).

**To Reproduce**

1. Change the departure time of a status manually via web/API
2. Try to reset it via `PUT /api/v1/status/:id` by setting `manualDeparture` or `manualArrival` to `null`
3. Request same status again
4. See that manual overwritten time hasn't changed.

**Expected behavior**
The overwritten time should be reset to null again.

**Comment by bendix-dev** [comment]
Can confirm this behaviour.
