### ISSUE TITLE
PWA color is not correct in dark mode

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/traewelling#1879]
**Describe the bug**
When using the dark mode with a PWA the given color code for the theme is not being changed.

**Screenshots**
![Screenshot_20230831-135335~2](https://github.com/Traewelling/traewelling/assets/4103693/07f50a78-abd2-40ca-86a3-cb213c290c4a)

**Comment by pascalwittler** [comment]
Multiple `theme_color` values are not part of the current PWA specification. A commonly implemented solution seems to be to insert the hex color value using Javascript.
