### ISSUE TITLE
Changing Webhook URL revokes all tokens

### ISSUE THREAD

**Issue by jheubuch** [Traewelling/traewelling#1881]
**Describe the bug**
When a new webhook URL is specified within the application settings, all existing and valid tokens are revoked.

**To Reproduce**

1. Create Application, Enable Webhooks
2. Claim Token
3. Update Webhook URL
4. See token is not valid anymore

**Expected behavior**
Tokens should not be invalidated after changing the webhook url

**Comment by marhei** [comment]
I can confirm this, I just tested it...
