### ISSUE TITLE
Prevent duplicate hashtag on event suggestions

### ISSUE THREAD

**Issue by NyCodeGHG** [Traewelling/traewelling#1885]
**Describe the bug**
When a user suggests an Event and enters the hashtag with the '#' in front, there are now 2 '#' in the field.

**To Reproduce**
1. suggest an event
2. enter something in the hashtag field starting with a '#'
3. traewelling adds another hashtag character by itself

**Expected behavior**
Only one hashtag character should be there.
traewelling should check if the user enters a hashtag character or not and adjust the hashtag accordingly.

**Screenshots**
![Screenshot_20230902-122339](https://github.com/Traewelling/traewelling/assets/37078297/d454cda9-7f0c-4d8b-9c05-f97a16300f77)

**Comment by MrKrisKrisu** [comment]
#1886
