### ISSUE TITLE
OAuth endpoint oauth/tokent grant_type refresh_token requires "code" field

### ISSUE THREAD

**Issue by M4rcDev** [Traewelling/traewelling#1939]
**Describe the bug**
I receive a 500 Page if I my app calls https://traewelling.de/oauth/token with the _client_id_, _grant_type=refresh_token_ and _refresh_token_

**To Reproduce**

- Create an OAuth (non-confidential) Application in traewelling
- Do the OAuth authorization to gain an _access_token_ and _refresh_token_
- Try to refresh the token:
```
curl --location 'https://traewelling.de/oauth/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=refresh_token' \
--data-urlencode 'refresh_token=def502os29[...]' \
--data-urlencode 'client_id=5'
```

The response is a 500-Error Page. Upon the next request the _refresh_token_ is invalid, although I have not received a new one due to the previous error.

**Expected behavior**
The server should respond with a json string that contains the new _access_token_ and if applicable a new _refresh_token_.

**Additional context**
Upon researching and debugging through a local traewelling instance I have found the root cause.
If I add a _code_ field to the request the issue is resolved. The _code_ field can have any value. Example:
```
curl --location 'https://traewelling.de/oauth/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=refresh_token' \
--data-urlencode 'refresh_token=def502os29[...]' \
--data-urlencode 'client_id=5' \
--data-urlencode 'code=This can be any value'
```
Then I receive a new _refresh_token_ and _access_token_ like I would expect.

The _code_ field is required due to a custom implementation in \App\Http\Controllers\Backend\Auth\AccessTokenController:32 that is extending the OAuth flow.
It seems to be related to the webhooks feature.

Additionally, as a developer I would expect that the application is not responding with a 500 error (which indicates that it crashed). This is happening due to a variable that is used from an Array but never validated if it actually exists in the request. If the field is required, I would expect a response like this:

```
{
    "error": "invalid_request",
    "error_description": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.",
    "hint": "Check the `code` parameter",
    "message": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed."
}
```
This would help developers to identify the issue faster and improve the overall experience.

**Comment by jheubuch** [comment]
Can confirm this behaviour
