### ISSUE TITLE
Iryo trains are not showing up in Träwelling

### ISSUE THREAD

**Issue by metamoof** [Traewelling/traewelling#1945]
**Describe the bug**
Iryo is one of four high-speed intercity operator in Spain. When attempting to check in, I was unable to find my train (13:55 Iryo 6140 Barcelona Sants-Madrid Puerta de Atocha)..

**To Reproduce**

1. Search for Barcelona Sants
2. Choose 13:50 as the departure time
3. Cannot see 13:55 Iryo 6140
![image](https://github.com/Traewelling/traewelling/assets/805751/064913c6-91e9-40b9-a465-fcb5cc65f89c)

**Expected behavior**
I expected to be able to check in to Iryo 6140.

**Screenshots**

![image](https://github.com/Traewelling/traewelling/assets/805751/064913c6-91e9-40b9-a465-fcb5cc65f89c)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Edge
- Version  117.0.2045.43 (Official build) (64-bit)

**Comment by marhei** [comment]
The timetable data is not published by Iryo in the European timetable database and can therefore not be found in Träwelling.

This is not a bug on the part of Träwelling, but an omission by Iryo.

**Comment by HerrLevin** [comment]
Sadly, @marhei is right. :/
