### ISSUE TITLE
API: Missing documentation for `/statistics` endpoint

### ISSUE THREAD

**Issue by marhei** [Traewelling/traewelling#1980]
There is the possibility to add a `from` and `until` parameter, but this is not documented.

**Comment by MrKrisKrisu** [comment]
Hmm, in der internen Spec ist es drin, aber es wird nicht in die Docs generiert. Muss man mal nachgucken, ob wir da die falsche Syntax für GET Parameter nutzen.

https://github.com/Traewelling/traewelling/blob/be4e4a1a58d5190ce48619b53ebcc18c2edfad4a/app/Http/Controllers/API/v1/StatisticsController.php#L238-L243
