### ISSUE TITLE
I would like to be able to search for the Trainnumber too

### ISSUE THREAD

**Issue by dieserMax** [Traewelling/traewelling#1982]
I think, it could be easier and faster to type in, the trainnumber.

thank you for programming this app, i like träwelling.☺️

**Comment by MrKrisKrisu** [comment]
Unfortunately, there is (to my knowledge) no publicly usable API that can provide us with corresponding data for checkin when a train number is entered. Therefore, this feature is unfortunately not currently implementable.

I'll close here, because the feature request already exists in #92.
