### ISSUE TITLE
All window-mounted js-libraries are dead

### ISSUE THREAD

**Issue by HerrLevin** [Traewelling/traewelling#2061]
Currently all js libraries that were "mounted" into the window (e.g. `window.notyf`) are broken due to the new vite setup. This also affects the MovingMarker-plugin for leaflet. 

Leaflet aside, this is a very central bug because users can't be informed about errors in their inputs or with the application.

**Comment by HerrLevin** [comment]
I'm not very good with vite and don't know a fast fix for all of this except manually creating a new vue component for every script tag in our project.

It's working when running `npm run dev` but breaks as soon as you're compiling with `npm run prod`.

Maybe @NyCodeGHG has some ideas/input for this behaviour? You're always good with stuff like this.

**Comment by NyCodeGHG** [comment]
I'll have a look into this later.
In general the whole window mounting thing shouldn't be done anymore, instead use the es module system

**Comment by NyCodeGHG** [comment]
seems like it's not really possible to integrate the templated script tags with vite :(
so it's also not really possible to migrate to es modules without rewriting most of the js code

**Comment by HerrLevin** [comment]
Bummer with the script tags. I'll rewrite some of it over the next couple of days. Thanks for the research! :)
