### ISSUE TITLE
Charts in 'Statistics' page show German string "Minuten" no matter the browser's language

### ISSUE THREAD

**Issue by Nagiphaaa** [Traewelling/traewelling#2077]
**Describe the bug**
All charts in the 'Statistics' page show the time in German (as "x **Minuten**") instead of in the user's browser language (in my case English, where it should be "x **minutes**"). I tested this for both English and French, and in both cases the same issue was present. I did not have German set as a fallback language in my browser settings.

**To Reproduce**
1. (Set browser to non-German language)
2. Go to the 'Statistics' page
3. Hovering over the pie charts or looking at the daily travel time charts reveal spent time as "x **Minuten**"

**Expected behavior**
The charts should display the 'minutes' string in the appropriate language, e.g. "x minutes"

**Screenshots**
![2023-10-21](https://github.com/Traewelling/traewelling/assets/90415429/ee03fdf7-5459-474f-9195-03fa44df175a)

**Desktop**
- OS: Windows 10
- Browser Firefox Nightly
- Version 120.0a1

I also tested this on my phone and came across the same issue:
**Smartphone**
- Device: Samsung Galaxy S21 5G
- OS: Android 13
- Browser Brave
- Version 1.59.117

**Comment by MrKrisKrisu** [comment]
Hmm, this is weird. This string is translated and there are variations for every language...

https://github.com/Traewelling/traewelling/blob/8f0cae6d80ceb0539e273e585087d95af87c0e2b/resources/views/stats/includes/chart_volume.blade.php#L61-L63

#### english translation
https://github.com/Traewelling/traewelling/blob/8f0cae6d80ceb0539e273e585087d95af87c0e2b/resources/lang/en.json#L534

#### italian translation
https://github.com/Traewelling/traewelling/blob/8f0cae6d80ceb0539e273e585087d95af87c0e2b/resources/lang/it.json#L440

**Comment by MrKrisKrisu** [comment]
It works perfectly in my local environment... this only happens at traewelling.de.

![image](https://github.com/Traewelling/traewelling/assets/4103693/403590f2-3e4e-47ed-9f08-aa9b6bf145e4)
