### ISSUE TITLE
API: Wrong error message for blocked user `/user/{username}/statuses` endpoint

### ISSUE THREAD

**Issue by marhei** [Traewelling/traewelling#2109]
### Describe the bug

If I have blocked a user and try to retrieve their statuses via the API, it incorrectly returns a localized error message that they have blocked me.
<img width="1154" alt="Capture d’écran 2023-11-08 à 20 24 46" src="https://github.com/Traewelling/traewelling/assets/10304183/b8342bb3-5790-4574-9e09-ad7d513d8ddf">
<img width="571" alt="Capture d’écran 2023-11-08 à 20 25 42" src="https://github.com/Traewelling/traewelling/assets/10304183/9c2b3eb7-c4c9-4f1b-8a0c-ef17e32891dd">

### Steps to reproduce

1. Block a user
2. Try to retrieve their statuses via the `/user/{username}/statuses`
3. Get the localized message that you're the person that is blocked by the user

**Comment by HerrLevin** [comment]
It also returns 404 instead of 403. 🤨

**Comment by marhei** [comment]
> It also returns 404 instead of 403. 🤨

That's what I already wrote here: https://github.com/Traewelling/traewelling/issues/1967 😇
