### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by TheJRB** [Traewelling/traewelling#2111]
### Describe the bug

All attempted check-ins at UK stations are returning the following error "An unknown error occurred. Please try again."

### Steps to reproduce

1. Select any UK station (e.g. Folkestone West)
2. Select a train
3. Attempt to check in

### Browser

Chrome

**Comment by HerrLevin** [comment]
There currently seems to be a problem with the data provided to us for the UK. Somehow, the stopovers have the suffix "+1" whereas the departure board has the timezon "Z". This is causing some problems. 

![telegram-cloud-photo-size-2-5366049522087745076-x](https://github.com/Traewelling/traewelling/assets/1267894/29ef6eff-9dd0-4c00-b451-477e23db878d)
![telegram-cloud-photo-size-2-5366049522087745075-x](https://github.com/Traewelling/traewelling/assets/1267894/cd637c20-ac41-43dd-8b76-22d7dc4cb9dc)

**Comment by HerrLevin** [comment]
Just found out that we also can't correctly filter the correct stations...

<img width="763" alt="image" src="https://github.com/Traewelling/traewelling/assets/1267894/927c74eb-45a3-4375-9b8b-7c565be17fd6">

**Comment by HerrLevin** [comment]
Should be fixed with #2113.

**Comment by MrKrisKrisu** [comment]
> Should be fixed with #2113.

soooooo...? it can be closed...?

**Comment by HerrLevin** [comment]
> > Should be fixed with #2113.
> 
> soooooo...? it can be closed...?

That was a "please give feedback wether it's fixed or not" :D
