### ISSUE TITLE
📊 Statistics

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/traewelling#222]
It would be nice, if Traewelling has some statistics about the own journeys. Charts can be beautiful!

Examples:
- [x] Time in vehicles by day/week/month
- [ ] Most used line numbers
- [x] Most used types (ICE, IC, RE, Bus, ...)
- [x] Most used trip-operators (depends on #227)
- [ ] Most uses stations
- [ ] longest journeys
- [ ] distance by day/week/month/year
- [ ] most delayed journeys
- [ ] most delayed lines (accumulated)

If you have more Ideas feel free to share here! :)

**Comment by MrKrisKrisu** [comment]
More ideas:

- Most used lines
- Most uses stations
- longest journeys
- distance by day/week/month/year

(ideas from @jheubuch - https://twitter.com/der_heubi/status/1479534364417474563)

**Comment by MrKrisKrisu** [comment]
- most delayed journeys
- most delayed lines (accumulated)

**Comment by michael-mezgo** [comment]
Hello, from my point of view it would be great if you can choose the period of the personal statistics yourself.
(Datepickers)

**Comment by MrKrisKrisu** [comment]
Yeah, time pickers would be great.
Until someone builds this, you can use the URL to choose a specific time period as of the page itself supports it already:
https://traewelling.de/stats?from=2022-07-01&to=2022-10-11

**Comment by michael-mezgo** [comment]
> Yeah, time pickers would be great.
> Until someone builds this, you can use the URL to choose a specific time period as of the page itself supports it already:
> https://traewelling.de/stats?from=2022-07-01&to=2022-10-11

Thanks for your quick reply and your work for Träwelling 😊. I love to use it.

**Comment by MrKrisKrisu** [comment]
I'm closing my old issue because I think adding new stats is a "do it once you see cool stats" feature. :)
