### ISSUE TITLE
Mastodon link isn't being deleted

### ISSUE THREAD

**Issue by jheubuch** [Traewelling/traewelling#2256]
### Describe the bug

When I remove my connection to Mastodon, a link to my Mastodon profile is still displayed on my Träwelling profile.
![image](https://github.com/Traewelling/traewelling/assets/60344409/55692411-3a7b-4622-a2f0-b380b621d2bc)
![image](https://github.com/Traewelling/traewelling/assets/60344409/fe563d57-a53e-4641-9067-d0a0e070bde0)

### Steps to reproduce

1. Add Mastodon connection
2. Go to Profile >> see Mastodon link
3. Remove Mastodon connection
4. Go to Profile >> see Mastodon link not being deleted

**Comment by jheubuch** [comment]
Ok weird, after a few minutes it despawned from my profile. Is this kind of scheduled task or sth?

**Comment by MrKrisKrisu** [comment]
> Ok weird, after a few minutes it despawned from my profile. Is this kind of scheduled task or sth?

Yes. The mastodon connection is cached. We should implement that the cached data is deleted with the removed connection.
