### ISSUE TITLE
Some journeys show up as SBB others as Schweizerische Bundesbahnen

### ISSUE THREAD

**Issue by albert180** [Traewelling/traewelling#2257]
### Describe the bug

Some journeys show up as "SBB" others as "Schweizerische Bundesbahnen". They should show up as one operator. (That SBB GmbH shows up as a separate operator is fine, as they operate regional railway services under contract for Baden-Württemberg
![Screenshot_20240107-224143](https://github.com/Traewelling/traewelling/assets/12116374/0b8775ff-3d70-4e70-951b-82e41d6aeec7)

### Steps to reproduce

See 1.

### Browser

Not relevant

**Comment by SoraCent** [comment]
![grafik](https://github.com/Traewelling/traewelling/assets/46794893/1b1e4bfd-db63-4333-971b-ca9a2ab41845)
I have the Same Issue

**Comment by marhei** [comment]
This is probably a problem of inconsistency in the data provided by the SBB rather than a problem with Träwelling.

**Comment by HerrLevin** [comment]
@marhei seems to be right with this. I'll close this issue since it's with our data provider.
