### ISSUE TITLE
Retroactive registration of trips not working

### ISSUE THREAD

**Issue by gufojoe** [Traewelling/traewelling#2288]
### Describe the bug

When trying to register a trip from the past, the departure board does not actually go to the respective time in the past.

### Steps to reproduce

1. Enter station name in "Station or Ril 100 identifier" field
2. Select date and time by clicking on "clock" symbol
3. Look at departure board and be sad

### Browser

several

**Comment by MrKrisKrisu** [comment]
I'm not sure if I understand the problem correctly. If I select a time in the past I also see the trains. Of course, the prerequisite for this is that these are still in the timetable. You can't go too far into the past. Can you give me an example request you've made?

**Comment by gufojoe** [comment]
How far in the past can trips be registered?

**Comment by jheubuch** [comment]
This depends on the data, DB is providing for the past and I think it can't be dated exactly. But when you can find your past journey in the DB Navigator, I think it should be also found on Träwelling service.

**Comment by MrKrisKrisu** [comment]
> This depends on the data, DB is providing for the past and I think it can't be dated exactly. But when you can find your past journey in the DB Navigator, I think it should be also found on Träwelling service.

I hope this answered your question. If not feel free to write again and we can reopen this issue. :)
