### ISSUE TITLE
Issue with the Location of TGV Haute Picardie Station

### ISSUE THREAD

**Issue by remythrn** [Traewelling/traewelling#2301]
### Describe the bug

There is a problem with the location of TGV Haute Picardie station, causing difficulties in recording journeys. Its geographical position is inaccurately marked and is not even on a railway track. This results in a straight-line path, like a bird's-eye view.
![IMG_8656](https://github.com/Traewelling/traewelling/assets/158100468/b76528de-8945-4f74-9b40-2d50501f32a4)

### Steps to reproduce

The exact geographical coordinates are: [2.8322318995333546, 49.85923434127017]

**Comment by MrKrisKrisu** [comment]
Sadly this is currently an Issue where we cannot help. Everytime a checkin to this stations happens, we are overwriting the data we are receiving from the data source "Deutsch Bahn HAFAS". So if we change the coordinates manually in the database the data will be wrong the next time someone check in here.
