### ISSUE TITLE
[Vue] Manual Trips: journeyNumber input is ignored

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/traewelling#2313]
### Describe the bug

When using the Vue Form the entered journeyNumber is not transferred with the request.

https://github.com/Traewelling/traewelling/blob/2d9e8abc7213a32f95fe21269d7afd67121b83dc/resources/vue/components/TripCreation/TripCreationForm.vue#L70-L72

### Steps to reproduce

1. Go to the Manual Trip Creator Form
2. Enter data + a journeyNumber
3. Submit Form
4. See, that the journeyNumber is missing

**Comment by HerrLevin** [comment]
Fixed by #2342
