### ISSUE TITLE
[Vue] Manual Trips: Inputs for Departure and Arrival are switched

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/traewelling#2314]
### Describe the bug

When creating a manual trip with stopovers the left input field is currently for the arrival and the right for departure. This should be switched.

### Steps to reproduce

1. Go to Manual Trip Creator Form.
2. Enter data (with Stopover)
3. Submit
4. See, that departure and arrival is switched

**Comment by HerrLevin** [comment]
Fixed by #2341
