### ISSUE TITLE
Check-in from Bergün/Bravougn not possible

### ISSUE THREAD

**Issue by dfriedlos** [Traewelling/traewelling#2390]
### Describe the bug

The connection search from Bergün/Bravuogn seems to work at first and redirects to https://traewelling.de/trains/stationboard?station=Berg%C3%BCn/Bravuogn

However, the departures of the trains from Bergün/Bravuogn station are not displayed there, but those from "Bergün/Bravuogn SBAD", the valley station of the distant Darlux chairlift: https://traewelling.de/trains/stationboard?station=Berg%C3%BCn/Bravuogn%20SBAD

Location-based search works to some extent: However, it never worked for me on the Pixel 7 Pro and Pixel 8 Pro either, sometimes on an iPhone under Safari and on a Pixel 7 under Chrome. On the Pixel 7 Pro and 8 Pro, I am then redirected to the post bus station at the train station, "Bergün/Bravuogn, staziun", where the chairlift appears in addition to the rarely running buses, instead of only the expected bus connections, and possibly, if linked to the train station, those of the trains.

Anklicken eines vorhandenen, per Mitfahren unter Träwelldroid getätigten" Check-ins ab Bergün/Bravuogn leitet auf https://traewelling.de/trains/stationboard?provider=train&station=8509197 um. Diese Nummer scheint soweit korrekt zu sein, aber auch so werden nur die Abfahrten ab "Bergün/Bravuogn SBAD" angezeigt.

### Steps to reproduce

1. Go to https://traewelling.de/dashboard
2. Search for Bergün/Bravougn
3. Choose Bergün/Bravougn as your starting point
4. Attempts to check-in to the trains departing there but not displayed

**Comment by MrKrisKrisu** [comment]
It seems that this issue belongs to the experimental check-in flow only. While we are debugging this, you can disable the experimental features in your settings and you'll be able to see the trips again.

![image](https://github.com/Traewelling/traewelling/assets/4103693/90292d58-681b-4b2d-b8b7-4a64d154680a)

![image](https://github.com/Traewelling/traewelling/assets/4103693/c754f029-4ac3-4295-93f2-9e1660133fc2)

**Comment by MrKrisKrisu** [comment]
This bug occured because of the `/` (slash) in the stations name. This issue will be resolved when the API endpoint supports station IDs.

**Comment by MrKrisKrisu** [comment]
Oups, no. This isn't fixed completely. @HerrLevin can you please migrate your Vue Code to the new departures endpoint?

**Comment by HerrLevin** [comment]
This has been fixed by #2426. (I mentioned #2426 inside itself instead of #2390)
