### ISSUE TITLE
Stations "for exit only" resulting in a crash

### ISSUE THREAD

**Issue by HerrLevin** [Traewelling/traewelling#24]
**Describe the bug**
If you're trying to check into a train which only stops to let people exit, Träwelling crashes, since there's no departure time.

**To Reproduce**
1. Go to any train with a "exit only" (e.g. ICE 619 in Frankfurt(M) Flughafen Fernbf, arrival 23:41)
2. Check in 

**Expected behavior**
Successful checkin

**Comment by jeyemwey** [comment]
Checking into the first time ICE619 arrives works for me (
![grafik](https://user-images.githubusercontent.com/2796271/75534311-246a9800-5a15-11ea-9e8d-64fdd0a5b28a.png)), but when starting the journey the first time there, it does not work.

Reproduce:

1. 
![grafik](https://user-images.githubusercontent.com/2796271/75534824-4cf29200-5a15-11ea-8117-9f51909b93ae.png)
2. Travel to Mannheim (or further).
3. _crash_

**Actual Behavior**: You see Frankfurt Hbf under "next stations" which makes sense but is not what we want. Maybe, add a "departure after" parameter?

![grafik](https://user-images.githubusercontent.com/2796271/75536248-b7a3cd80-5a15-11ea-8b3c-8c34d8d8648f.png)

**Comment by MrKrisKrisu** [comment]
Works for me now. I can travel from Frankfurt Hbf to Mannheim and from Frankfurt Fern. to Mannheim without problems. Please reopen this issue if this error still occurs.

![image](https://user-images.githubusercontent.com/4103693/107889567-d693bc00-6f13-11eb-994b-98d6f9f6e823.png)
![image](https://user-images.githubusercontent.com/4103693/107889572-deebf700-6f13-11eb-9f1f-b58f3c87c18f.png)
![image](https://user-images.githubusercontent.com/4103693/107889603-1c508480-6f14-11eb-989e-902cb0d91877.png)
