### ISSUE TITLE
Intermediate stops not appearing

### ISSUE THREAD

**Issue by Gaelan** [Traewelling/traewelling#2401]
### Describe the bug

For the last month or so, Traewelling has for some reason not shown any intermediate stops when entering a journey:

![IMG_7606](https://github.com/Traewelling/traewelling/assets/4495750/c4938c17-8575-482c-85dd-ba0f175d05d7)

I can enter a journey to the final stop using the “fast forward” icon, but that’s it. 

### Steps to reproduce

Try to enter any journey on a UK train, as far as I can tell; I’ve mostly been doing journeys from Leuchars(St.Andrews)

### Browser

iOS Safari

**Comment by fabiancdng** [comment]
I noticed this issue as well on various UK connections:

![Screenshot 2024-03-10 at 13 34 12](https://github.com/Traewelling/traewelling/assets/36338179/ed2db587-2f4f-44ad-bc2d-8e8a27620323)

Interestingly, the intermediate stops are showing when turning on the experimental feature setting:
![Screenshot 2024-03-10 at 13 34 29](https://github.com/Traewelling/traewelling/assets/36338179/4d7e8857-fe75-4c94-9fc6-aabb0306da61)

---

![Screenshot 2024-03-10 at 13 35 13](https://github.com/Traewelling/traewelling/assets/36338179/769ed263-2e12-441e-a4fe-3490968e564d)

However, after enabling that setting, the check-in to any stop (even the final one) results in a 422 error:

![Screenshot 2024-03-10 at 13 36 52](https://github.com/Traewelling/traewelling/assets/36338179/eb2ad3c0-31af-492f-9570-d0511e09c933)
