### ISSUE TITLE
No error handling on manual trip creation form

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/traewelling#2417]
### Describe the bug

When creating a manual trip and an error occurred, just nothing happens. There is no error message.

### Steps to reproduce

1. Create manual trip maybe with a bug from #2416 
2. submit
3. nothing happens

**Comment by HerrLevin** [comment]
I mean... technically that's a server error since the server returns a 500. :D

**Comment by MrKrisKrisu** [comment]
In that case there should be a generic error message like "An unknown error occured.".
But nothing is just bad for the User. :D
