### ISSUE TITLE
Own tags always displayed in upper case letters

### ISSUE THREAD

**Issue by 0AgentSmith** [Traewelling/traewelling#2460]
### Describe the bug

For a few weeks now (maybe since issue #2335 was fixed? idk), tags constisting of letters are somehow always displayed using UPPER CASE LETTERS even though they were typed using only lower case letters.
"Test" becomes "TEST", "test" becomes "TEST", and so on. I've seen this happen now on an Ipad as well as on my laptop running Win10 and Firefox 124

### Steps to reproduce

1. Check into a journey
2. Add a tag that also has letters in it

![Bug on Apple](https://github.com/Traewelling/traewelling/assets/163422528/ed334b92-85b0-4e31-859f-b452bd8f34ff)
(Apple Ipad using Safari)

![Bug on PC](https://github.com/Traewelling/traewelling/assets/163422528/d7bf57a5-5200-4459-9388-fad99a891af2)
(Laptop)

**Comment by HerrLevin** [comment]
It's been that way since #2265, because buttons are uppercase in mdbootstrap. Not necessarily an issue imho. 

I would propose, changing all tags to uppercase.

**Comment by MrKrisKrisu** [comment]
> It's been that way since #2265, because buttons are uppercase in mdbootstrap. Not necessarily an issue imho.

I see it as an issue because it is unwanted behavior. Contents of tags can contain case sensitive text.
