### ISSUE TITLE
Wrong Polylinr

### ISSUE THREAD

**Issue by sinsa92** [Traewelling/traewelling#2515]
### Describe the bug

The Polyline is completely wrong when checking into a train towards BNFI (Bern Fischermätteli) to Bern Europaplatz from Bern. This does not affect the lines towards Laupen/Fribourg.

![IMG_0873](https://github.com/Traewelling/traewelling/assets/36137659/9e88f263-e648-4007-bc0d-9778dfdd1228)

### Steps to reproduce

1. Go to Bern
2. Check in on either S3 Belp, S31 Belp, S6 Schwarzenburg until Bern, Europaplatz
3. The Polyline is horribly wrong

The polyline should look similar to S1 Fribourg/Freiburg or S2 Laupen to Europaplatz.

### Browser console logs

```bash
Cannot check on mobile
```

### Browser

Safari

**Comment by HerrLevin** [comment]
That's a known issue with brouter. Hopefully it will be fixed with #2516.
