### ISSUE TITLE
Manual check-in doesn't work for specific stop

### ISSUE THREAD

**Issue by metrophil** [Traewelling/traewelling#2524]
### Describe the bug

I'm trying to create a manual trip from "Spöck Richard-Hecht-Schule, Stutensee", however I always get the error message "Die Start-ID ist nicht in den Zwischenstopps". Manual trips from elsewhere, as well as manual trips to Spöck work for me, just not when Spöck is the starting stop. User @d3d9 reported they have the same problem.

### Steps to reproduce

1. Go to Create manual trip
2. Enter "Spöck Richard-Hecht-Schule, Stutensee" as starting point
3. Enter any other stop as end point (e.g. "Durlach Turmberg, Karlsruhe")
4. Try saving the trip
![Screenshot_20240423-162758~2](https://github.com/Traewelling/traewelling/assets/72109316/e023f17b-8654-444c-aebe-5dc53f125a30)

**Comment by MrKrisKrisu** [comment]
I know the error occurs occasionally. But I can (no longer?) reproduce it. Can you still reproduce it with the data itself or have you found another station with which I can debug?

![image](https://github.com/Traewelling/traewelling/assets/4103693/86096ac7-aa3f-4365-b918-8ffb8f0370e9)
