### ISSUE TITLE
Fehlermeldung "Die Start-ID ist nicht in den Zwischenstops"

### ISSUE THREAD

**Issue by Atlantiko** [Traewelling/traewelling#2529]
### Describe the bug

Beim Trip erstellen, wenn ich von Eisenstadt aus eine Fahrt erstellen möchte kommt immer die Fehlermeldung "Die Start-ID ist nicht in den Zwischenstops"

### Steps to reproduce

1. Trip erstellen
2. Als Startbhf Eisenstadt auswählen
3. Ziel Bahnhof egal
4. Alle Daten eingeben
5. Einchecken
6. Fehlermeldung 

### Browser

Opera, Chrome, Firefox

**Comment by metrophil** [comment]
Similar problem as in #2524

**Comment by MrKrisKrisu** [comment]
I know the error occurs occasionally. But I can (no longer?) reproduce it. Can you still reproduce it with the data itself or have you found another station with which I can debug?

![image](https://github.com/Traewelling/traewelling/assets/4103693/1047bb23-8e3f-4bca-9f9a-3883662c48d4)
