### ISSUE TITLE
Fahrweg lädt nicht (Einzelfall Fahrt Tram) 

### ISSUE THREAD

**Issue by 401wagen1** [Traewelling/traewelling#2572]
### Describe the bug

Wir sitzen zu dritt in der S2 (Rheinstetten-oberreut).
Jedes andere Verkehrsmittel lässt den Fahrweg anzeigen jedoch in diesem Fall sind in Karlsruhe Baustellen und das Ziel der Fahrt ist Oberreut angegeben, welches jedoch eine durchbindunf der VBK S2 rheinstetten-Hauptfriedhof und VBK 4 Hauptfriedhof-Oberreut ist.) Wir vermuten, dass hier bei dieser linienverknüpfung der Fehler liegt.
Start der S2 war in Rheinstetten 18:15

### Steps to reproduce

1. Haltestelle Forchheim, Hauptstraße wählen.
2. Bahn wählen
3. Es lädt ewig

### Browser

Träveldroid

**Comment by MrKrisKrisu** [comment]
> ### Steps to reproduce
> 1. Haltestelle Forchheim, Hauptstraße wählen.
> 2. Bahn wählen
> 3. Es lädt ewig

Ich kann die Schritte so nicht nachvollziehen - ich kann einchecken und auch der Fahrweg auf der Karte wird dargestellt. Hast du noch weitere Infos was für ein Problem du hast?

![image](https://github.com/Traewelling/traewelling/assets/4103693/5e1151cc-b463-4822-b18b-86434cdb4483)

**Comment by rugk** [comment]
Hmm could be related to many server errors/downtime happenning recently. I also have the problem.

![Screenshot_20240524-180726_1](https://github.com/Traewelling/traewelling/assets/11966684/65c7a5a5-9893-40fb-ac62-15bcf3d17bb7)

18:07 today e.g. in case your have some logging/monitoring.

This was also a tram check-in. It was really slow and in Traeveldroid it was loading and did not stop anything, so I switched to the web version.

**Comment by rugk** [comment]
Again. Search works flawless, only when you load the check-in options, i.e. the target station to check/get out, it fails with 500 errors or loads endless.

**Comment by MrKrisKrisu** [comment]
> Again. Search works flawless, only when you load the check-in options, i.e. the target station to check/get out, it fails with 500 errors or loads endless.

This is because of database table locks, which we are unfortunately currently experiencing due to unperformant code. This happens at times when a lot of people are active on Träwelling.

**Comment by MrKrisKrisu** [comment]
> > ### Steps to reproduce
> > 
> > 1. Haltestelle Forchheim, Hauptstraße wählen.
> > 2. Bahn wählen
> > 3. Es lädt ewig
> 
> Ich kann die Schritte so nicht nachvollziehen - ich kann einchecken und auch der Fahrweg auf der Karte wird dargestellt. Hast du noch weitere Infos was für ein Problem du hast?
> 
> ![image](https://private-user-images.githubusercontent.com/4103693/332296444-5e1151cc-b463-4822-b18b-86434cdb4483.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNzM1NzUsIm5iZiI6MTcxNzE3MzI3NSwicGF0aCI6Ii80MTAzNjkzLzMzMjI5NjQ0NC01ZTExNTFjYy1iNDYzLTQ4MjItYjE4Yi04NjQzNGNkYjQ0ODMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzFUMTYzNDM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTI3NzRiNmJjMGE1NDg3MWQwYTFiNjAzOGQ4NjQyNjE0ZDYxMjU0NmE2MGY5N2I5ZmYwZWIxNGMwZGM2NDFjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kF3i1YUj1ITuP6S_VTq4HY0KyN3vi0N1AF7GxwipFgI)

Wie hier bereits geschrieben kann ich das nicht reproduzieren, bei mir hat es funktioniert. Daher mache ich mal zu, sag bescheid, wenn es doch noch akut ist.

(@rugk, da dein Thema ein anderes ist als dieses Issue: Performance Issues sollten akut behoben sein, wenn nicht, mach bitte ein eigenes Issue auf.)
