### ISSUE TITLE
Create a own journe

### ISSUE THREAD

**Issue by EisenbahnfotografWesterwamd** [Traewelling/traewelling#2577]
### Describe the bug

Das Feature "Create a own journey" funktioniert momentan leider nicht und ich habe mich auch bei Freunden gemeldet bei ihnen funktioniert es auch nicht... Also ich gebe meine beginn Station und aussteig Station an sobald ich auf speichern gehe kommt aber nicht mehr als einfach das ich oben nur die Linie sehe aber kein Ort mehr zum einchecken oder auch bei manchen Station die man als Start punkt angeben möchte wird dann immer sobald man auf Speichern klickt "Die Haltestelle ist nicht in den zwischen stopps" das ist sehr schade alles undwäre schön wenn es gefixt werden könnte

### Steps to reproduce

1. Gehen Sie auf create a own journey 2. Geben Sie Ihre Beginn und end Station und Abfahrt und ankunft(Zwischenstopp optional) halt generell alles und dann auf speichern 3. Dann kann man keine Station mehr auswählen wo man hin möchte

**Comment by MrKrisKrisu** [comment]
Das sollte jetzt mit Release [v1.65](https://github.com/Traewelling/traewelling/releases/tag/v1.65) behoben sein ([Änderung](https://github.com/Traewelling/traewelling/pull/2578)). :)
