### ISSUE TITLE
Inconsistent UI: No new event selection with "drive along" feature

### ISSUE THREAD

**Issue by sanojkl** [Traewelling/traewelling#2601]
### Describe the bug

When using the drive along feature there is not the new event selection button, there is still the old list.

### Steps to reproduce

1. Check in normally, in the last step is the options screnen with the event selection

2. go to "drive along" on checkin from an other person.

**Comment by HerrLevin** [comment]
Yes. That's because the new Check-In UI is an experimental feature. This is (currently) intended behavior. But it will be adapted soon.
