### ISSUE TITLE
500 when accepting follow requests

### ISSUE THREAD

**Issue by HerrLevin** [Traewelling/traewelling#2651]
### Describe the bug

In very rare cases it's possible to provoke an error 500 (AlreadyFollowingException) when accepting a follow request

### Steps to reproduce

This cannot easily be reproduced without manipulating the database.

1. Table `follows`
```
id|user_id|follow_id|created_at             |updated_at             |
--+-------+---------+-----------------------+-----------------------+
 1|      1|        2|2024-04-19 13:07:10.000|2024-04-19 13:07:10.000|
 ```
 
2.  Table `follow_requests`
 ```
 id|user_id|follow_id|created_at             |updated_at             |
--+-------+---------+-----------------------+-----------------------+
  1|      1|        2|2024-04-19 12:00:01.000|2024-04-19 12:00:01.000|
 ```
 
3. Accept follow-reqeust

**Comment by HerrLevin** [comment]
Idea: try/catch around the follow acceptance and just remove the follow request if THIS exception occurs

**Comment by MrKrisKrisu** [comment]
I cannot find the cause of your problem. We have two endpoints APIv1 and legacy frontend. Both Endpoints catches the AlreadyFollowingException and don't return HTTP 500 then.

https://github.com/Traewelling/traewelling/blob/a55c811bff153a482eb68f080984ae721f9a5887/app/Http/Controllers/API/v1/FollowController.php#L63-L64

https://github.com/Traewelling/traewelling/blob/a55c811bff153a482eb68f080984ae721f9a5887/app/Http/Controllers/FrontendUserController.php#L78-L79

**Comment by HerrLevin** [comment]
No, it's in 

https://github.com/Traewelling/traewelling/blob/a55c811bff153a482eb68f080984ae721f9a5887/app/Http/Controllers/Backend/User/FollowController.php#L70-L79
