### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Feuergamer07** [Traewelling/traewelling#2671]
### Describe the bug

Kein öpnv Nahverkehr Check-in mehr möglich

### Steps to reproduce

INSERT failed: DBD::Pg::st execute failed: ERROR: value too long for type character varying(128) at lib/Travelynx/Model/InTransit.pm line 175

**Comment by NyCodeGHG** [comment]
Are you sure this is a traewelling issue?
The error message looks a lot more like you meant to open an issue at https://travelynx.de/

**Comment by MrKrisKrisu** [comment]
I also think that Travelynx is meant here. Please open a corresponding issue there. :)

https://github.com/derf/travelynx
