### ISSUE TITLE
Cannot check in for replacement trains (Ersatzzug)

### ISSUE THREAD

**Issue by ET430-Rosenheim** [Traewelling/traewelling#2674]
### Describe the bug

When checking into a replacement train, the select destination screen keeps loading and doesn't let me choose the alighting stop

### Steps to reproduce

1. Select a replacement train (e.g. ICE 2911)
2. No station list is shown

### Browser

Chrome, Träwelldroid

**Comment by gglnx** [comment]
Same for `ICE 2907`, the server response for `GET https://traewelling.de/api/v1/trains/trip?hafasTripId=2%7C%23VN%231%23ST%231717614449%23PI%230%23ZI%232116333%23TA%230%23DA%23110624%231S%238011102%231T%231051%23LS%238000261%23LT%231508%23PU%2380%23RT%232%23CA%23ICE%23ZE%232907%23ZB%23ICE+2907%23PC%230%23FR%238011102%23FT%231051%23TO%238000261%23TT%231508%23&lineName=ICE+2907&start=8098160`:

```
{
    "message": "Server Error",
    "reference": "666813a094162"
}
```

**Comment by marhei** [comment]
The same happens not only to replacement trains but also to all ICE line 41 trains that are diverted due to track damage. For example `ICE 820`:

`GET https://traewelling.de/api/v1/trains/trip?hafasTripId=2%7C%23VN%231%23ST%231717614449%23PI%230%23ZI%232116664%23TA%230%23DA%23110624%231S%238000261%231T%23553%23LS%238000085%23LT%231050%23PU%2380%23RT%233%23CA%23ICE%23ZE%23820%23ZB%23ICE%20%20820%23PC%230%23FR%238000261%23FT%23553%23TO%238000085%23TT%231050%23&start=5614&lineName=ICE%20820`:

```
{
    "message": "Server Error",
    "reference": "666814da362a7"
}
```

**Comment by MrKrisKrisu** [comment]
> The same happens not only to replacement trains but also to all ICE line 41 trains that are diverted due to track damage. For example `ICE 820`:
> 
> `GET https://traewelling.de/api/v1/trains/trip?hafasTripId=2%7C%23VN%231%23ST%231717614449%23PI%230%23ZI%232116664%23TA%230%23DA%23110624%231S%238000261%231T%23553%23LS%238000085%23LT%231050%23PU%2380%23RT%233%23CA%23ICE%23ZE%23820%23ZB%23ICE%20%20820%23PC%230%23FR%238000261%23FT%23553%23TO%238000085%23TT%231050%23&start=5614&lineName=ICE%20820`:
> 
> ```
> {
>     "message": "Server Error",
>     "reference": "666814da362a7"
> }
> ```

```
2024-06-11 09:11:54] production.ERROR: Der Fahrplan konnte nicht geladen werden. Bitte versuche es gleich erneut. {"reference":"666814da362a7","userId":3105,"exception":"[object] (App\\Exceptions\\HafasException(code: 0): Der Fahrplan konnte nicht geladen werden. Bitte versuche es gleich erneut. at /var/www/traewe>
[stacktrace]
#0 /var/www/traewelling-prod/app/Http/Controllers/HafasController.php(391): App\\Http\\Controllers\\HafasController::fetchRawHafasTrip()
#1 /var/www/traewelling-prod/app/Http/Controllers/HafasController.php(356): App\\Http\\Controllers\\HafasController::fetchHafasTrip()
#2 /var/www/traewelling-prod/app/Http/Controllers/Backend/Transport/TrainCheckinController.php(273): App\\Http\\Controllers\\HafasController::getHafasTrip()
#3 /var/www/traewelling-prod/app/Http/Controllers/API/v1/TransportController.php(282): App\\Http\\Controllers\\Backend\\Transport\\TrainCheckinController::getHafasTrip()
#4 /var/www/traewelling-prod/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\API\\v1\\TransportController->getTrip()
#5 /var/www/traewelling-prod/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#6 /var/www/traewelling-prod/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
```

**Comment by MrKrisKrisu** [comment]
This belongs to #2672.

**Comment by MrKrisKrisu** [comment]
Unfortunately, there is nothing we can do here. We (@HerrLevin  and I) have just tested everything possible.

It is not Träwelling's fault.

It is not [DB-Rest](https://github.com/derhuerst/db-rest)'s fault.

It is not the [hafas-client](https://github.com/public-transport/hafas-client)'s fault.

It is a HAFAS error - but only on some journeys.

**Comment by MrKrisKrisu** [comment]
> It is not Träwelling's fault.

It was Träwelling's fault.
https://github.com/Traewelling/traewelling/pull/2681

**Comment by HerrLevin** [comment]
Further investigation found that I'm responsible. It should all work now. (See #2681)

**Comment by HerrLevin** [comment]
> > It is not Träwelling's fault.
> 
> It was Träwelling's fault. #2681

oh, you were faster. :D
