### ISSUE TITLE
Login redirects to "/notifications/latest"

### ISSUE THREAD

**Issue by aledjones** [Traewelling/traewelling#28]
**Describe the bug**
After login, the user gets redirected to `/notifications/latest`. This results in the delivery of the corresponding JSON file. 

**To Reproduce**
1. Go to login page, unauthenticated.
2. Login with credentials (tested with mail login, not social)
4. you get served a JSON file.

**Expected behavior**
After login, the user gets redirected to his dashboard.

**Desktop (please complete the following information):**
 - OS: Debian 10 Buster
 - Browser: Mozilla Firefox
 - Version: `Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0`

**Additional context**
Commit: [1c55723227b1399d623ad3f4906420eebd8bb130](https://github.com/Traewelling/traewelling/commit/1c55723227b1399d623ad3f4906420eebd8bb130)

**Comment by HerrLevin** [comment]
Are you in dev or prod environment?

Am So, 1. Mär 2020, um 12:27, schrieb Jonas Möller:

**Comment by aledjones** [comment]
dev env

Should I post my .env file contents for clarification?

**Comment by HerrLevin** [comment]
No, I have an idea.

There was a quickfix pre-release to fix iOS PWA-Problems. Could you please start the application as prod?

Am So, 1. Mär 2020, um 12:29, schrieb Jonas Möller:

**Comment by aledjones** [comment]
Same result with prod environment

**Comment by jeyemwey** [comment]
Hey @aledjones - does this bug still occur?

**Comment by aledjones** [comment]
Bug does still occur. +1 other bug, but I'll open an extra issue for that.

**Comment by HerrLevin** [comment]
I found the source of the error!
It seems to be the ` fetch` -method in `resources/js/components/notifications-board.js` .
