### ISSUE TITLE
Spanish doesn't appear on language list

### ISSUE THREAD

**Issue by garridinsi** [Traewelling/traewelling#2866]
### Describe the bug

The Spanish translation doesn't appear on the language list, but all translation json changes are commited on this repo and the status on the translation platform is 100%

Probably it needs something more than the language json.

### Steps to reproduce

1. Go to Traewelling
2. Scroll down
3. Open language selector
4. Spanish not found

**Comment by MrKrisKrisu** [comment]
Thanks for the tip. We will have to add the languages manually when they are translated.
