### ISSUE TITLE
Not all stations are shown when creating a custom journey

### ISSUE THREAD

**Issue by JoohanV** [Traewelling/traewelling#2909]
### Describe the bug

When creating a custom journey, the list of stations to choose from as a departure or arrival is not complete, even when the query is an exact match with the station name. This seems to only create problems with short names that are also common as parts of other names, such as Oss or Elst (both in the Netherlands)
![Screenshot_20240911-213212_Firefox](https://github.com/user-attachments/assets/126cdeed-ee4b-4fb2-b200-17ffb02a97ad)

### Steps to reproduce

1. Try to enter a custom departure/arrival
2. Station you're looking for unavailable in list

**Comment by HerrLevin** [comment]
Okay, nvm. Didn't fix it on prod. :(

**Comment by MrKrisKrisu** [comment]
fixed with #3056
