### ISSUE TITLE
Export api endpoint redirects to frontend export

### ISSUE THREAD

**Issue by AdriDevelopsThings** [Traewelling/traewelling#2911]
### Describe the bug

I'm trying to export my traewelling checkins with this [function](https://traewelling.de/export). Clicking on CSV (Human or Machine Readable Headings either) sends a POST request to `https://traewelling.de/api/v1/export/statuses` but this endpoint just redirects me to `https://traewelling.de/export` again.

### Steps to reproduce

1. Go to [https://traewelling.de/export](https://traewelling.de/export)
2. Click on CSV (Human or Machine Readable Headings)

### Browser

Chrome

**Comment by AdriDevelopsThings** [comment]
This problem only seems to exist for long periods such as the selection of more than one year. Maybe the frontend should show an error message like "Period is too long".

**Comment by HerrLevin** [comment]
Could/should be fixed with #2444 2444

**Comment by MrKrisKrisu** [comment]
seems to be fixed
