### ISSUE TITLE
Status cannot be liked/starred

### ISSUE THREAD

**Issue by rugk** [Traewelling/traewelling#2918]
### Describe the bug

When visiting Traewelling, I do not see the star button/count anymore. Thus, i also cannot star it.
Additionally, I also don't see it in Traeweldroid and there I cannot see the current star count/who starred it. (But actually I also don't see it on the website.)

Screenshot:
![grafik](https://github.com/user-attachments/assets/b333bfb9-9dfb-415a-8d31-255a615de145)

Same/reproduced on mobile too, BTW.

In the past, I've also enabled/disabled the feature preview mode, so maybe that is related. Also tried that again, but this does not change the bug.

Related: I found an old issue https://github.com/Traewelling/traewelling/issues/348 about this.

### Steps to reproduce

1. Go to https://traewelling.de/dashboard
2. Like any status.

### Browser console logs

```bash
empty
```

### Browser

Firefox

**Comment by marhei** [comment]
It's probably just a user who has disabled the ability to have their statuses liked.

**Comment by rugk** [comment]
No no, it's for all statuses. And I checked with another user they can star the status.

**Comment by MrKrisKrisu** [comment]
Do you have disabled this in your own settings?

**Comment by rugk** [comment]
See here some more:
![grafik](https://github.com/user-attachments/assets/7476ea7d-66da-4553-9ce0-fcb2d69a9ca1)

**Comment by marhei** [comment]
> Do you have disabled this in your own settings?

Yes, he did!

**Comment by rugk** [comment]
![grafik](https://github.com/user-attachments/assets/86292418-feed-4015-9067-268ba771829f)

Here? The checkbox is not checked?

That settings somehow got reset or I am very stupid, because I have alos enabled auto-hiding status'es hmm…

**Comment by rugk** [comment]
Now it works after enabling this checkbox, strange…

I never knowingly disabled that and as said also the auto-hide setting AFAIK was set differently…

(Thanks in any case!)
