### ISSUE TITLE
Strecke Spiez->Interlaken

### ISSUE THREAD

**Issue by Drystan04** [Traewelling/traewelling#2970]
### Describe the bug

Bei der Strecke Spiez Interlaken (CH) nimmt es die Kilometer in Luftlinie und nicht die Tatsächliche Strecke

### Steps to reproduce

1. Spiez eingeben 2. Zug nach Interlaken ost anwählen 3. Einchecken

### Browser

Chrome

**Comment by MrKrisKrisu** [comment]
Hi! Das ist ein bekanntes Verhalten im Ausland (nicht Deutschland).
Hier ist beschrieben, warum das passiert:

https://help.traewelling.de/features/map/
