### ISSUE TITLE
Public check-ins arent shown for non-followers on private profile

### ISSUE THREAD

**Issue by forest-cat** [Traewelling/traewelling#2999]
### Describe the bug

When creating a check-in on a private profile and setting the check-in to "unlisted" or "public", its not visible without following the account.

### Steps to reproduce

1. Set your profile to private
2. Create a check-in and set its visibility to "public" or "unlisted"
3. Click on share and open the link without being logged in
4. Its says 401 unauthorized

### Browser

Firefox

**Comment by MrKrisKrisu** [comment]
Hey, thanks for the issue. Please see #2959 for an existing discussion.
