### ISSUE TITLE
Cannot create manual journeys starting in Chop (Ukraine)

### ISSUE THREAD

**Issue by thatjade** [Traewelling/traewelling#3054]
### Describe the bug

When trying to create a new manual journey starting in Chop I cannot select Chop as starting point. Regular journeys in Chop are no problems.
![IMG_0204](https://github.com/user-attachments/assets/15158402-1fb6-4489-8001-b9b1915548bd)

### Steps to reproduce

- Choose Chop in dashboard
- Create manual journey
- Try putting chop as departure.

### Browser

Firefox/Safari

**Comment by Kya-ra** [comment]
I think this matches my issue for Wick, #3047
