### ISSUE TITLE
Translate times

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/traewelling#320]
**Describe the bug**
Times should be included in the translation files, as they may be displayed differently in other languages.

Example: france: 00h31 instead of 00:31

**Screenshots**
![image](https://user-images.githubusercontent.com/4103693/117959984-d6416c00-b31c-11eb-9165-eb0a796b7320.png)

**Comment by HerrLevin** [comment]
Maybe we could use moment.js?

**Comment by MrKrisKrisu** [comment]
Why make it complicated if we can just use the translation template? The times are not handled by javascript.
