### ISSUE TITLE
Status cannot be liked

### ISSUE THREAD

**Issue by jheubuch** [Traewelling/traewelling#348]
**Describe the bug**
If I press the like button on any status, nothing happens. Instead a error message is put out on the JS browser console:
![image](https://user-images.githubusercontent.com/60344409/118480457-90b4e280-b712-11eb-8f3b-42eabc49fe35.png)

**To Reproduce**
1. Go to Dashboard page
2. Press the fav-button on any status

**Expected behavior**
HTTP request for liking the state will be sent and the star's state will change

**Comment by MrKrisKrisu** [comment]
Thanks for creating the Issue!
This will be fixed in #344
