### ISSUE TITLE
Dates on statistics page are not localized

### ISSUE THREAD

**Issue by NilsZiegfeld** [Traewelling/traewelling#379]
**Describe the bug**
The dates on the statistics page all use the german DD.MM.YYYY format.

**Expected behavior**
Dates should be localized, e.g. YYYY-MM-DD in swedish

**Comment by MrKrisKrisu** [comment]
Thank you for reporting! :) I have fixed the error. It will take a few more days to be visible on traewelling.de.

**Comment by NilsZiegfeld** [comment]
Unfortunately, the attempt to solve this issue created a few new problems:
* The dates in the headline of the statistics page are still in the german `DD.MM.YYYY` format
* The dates in the footer of the "Global statistics" column are now completely broken, e.g. `2021202120212021-MayMay-MonMon` instead of `2021-05-03` in swedish

These problems do not depend on the selected language.

**Comment by MrKrisKrisu** [comment]
See #388
