### ISSUE TITLE
Visiting a profile without linked Mastodon account throws error 500

### ISSUE THREAD

**Issue by aledjones** [Traewelling/traewelling#39]
**Describe the bug**
Visiting a profile without linked Mastodon account throws error 500. 

**To Reproduce**
1. Create a profile without Mastodon, so that no Mastodon server domain is set (e.g. in local testing)
2. Go to own profile
3. See error

**Expected behavior**
The profile gets displayed.

**Screenshots**
![Screenshot_2020-03-23 Whoops There was an error ](https://user-images.githubusercontent.com/649142/77316716-3553b400-6d0a-11ea-9aee-2aac9fc48661.png)

**Desktop:**
 - OS: Debian 10 Buster
 - Browser: Firefox ESR
 - Version: `Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0`

**Additional context**
I cannot confirm if this also happens in production, but in every testing and dev installation of mine it happens.

**Comment by jeyemwey** [comment]
Ah dang thats on me.
