### ISSUE TITLE
Show events only in a specified distance

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/traewelling#390]
I would like to be able to specify a radius in kilometers in the admin dashboard when creating events, so that only users who are within the radius will see the event. Since we also have the coordinates of the start and end of each CheckIn, this should not be a problem.

**Comment by jeyemwey** [comment]
With our "ban" on local events (#1203), I see this as resolved.

/vote close

**Comment by MrKrisKrisu** [comment]
> /vote close

ack.
