### ISSUE TITLE
Add regionalExp as a transport_type

### ISSUE THREAD

**Issue by jeyemwey** [Traewelling/traewelling#398]
**Describe the bug**
The statistics tool tries to use `transport_type.regionalExp` sometimes, but the translation key is not available.

**Expected behavior**
`Regional Express` services are shown next to the other transport types.

**Screenshots**
![image](https://user-images.githubusercontent.com/2796271/120938674-52f51980-c714-11eb-99c6-ce460c812eda.png)

**Additional context**
Originally reported by: https://twitter.com/f2k1de/status/1401629305801748487

**Comment by MrKrisKrisu** [comment]
Closed in #399
