### ISSUE TITLE
🌙 DarkMode

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/traewelling#406]
I want to spare my eyes as I pursue my passion for travel in the dark nights, swinging from train to train. A dark mode would help there. All black. `#000`.

**Comment by Oxbowatos** [comment]
Is this enhancement going to be added soon ? It would be a nice feature :D

**Comment by MrKrisKrisu** [comment]
Maybe we can use the new color mode introduced in [bootstrap v5.3-alpha1](https://getbootstrap.com/docs/5.3/customize/color-modes/).
Therefore we just need to change a single tag.

Unfortunately we use mdbootstrap, so we need to wait until this gets merged to them or build our own style.
