### ISSUE TITLE
Date form field placeholder text overlaps form field title

### ISSUE THREAD

**Issue by NilsZiegfeld** [Traewelling/traewelling#420]
**Describe the bug**
On the events page, the placeholder text of the date form fields overlaps the title of the form field

**Expected behavior**
Placeholder does not overlap form field title, or no placeholder text is shown

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/17621496/121405175-03edf500-c95d-11eb-8588-c9faab7a4f0e.png)

**Desktop**
 - OS: Windows
 - Browsers: Firefox, Chrome, Edge

**Mobile**
 - OS: Android
 - Browser: Firefox

**Additional context**
Does not depend on the selected language

**Comment by MrKrisKrisu** [comment]
mdb-ui-kit fixed this, so it is no longer up to date.
