### ISSUE TITLE
Content is partially cut off on events page on small screens

### ISSUE THREAD

**Issue by NilsZiegfeld** [Traewelling/traewelling#421]
**Describe the bug**
On the events page, content is partially cut off on small screen sizes

**To Reproduce**
1. Go to events page on a mobile device or emulate small screen size in browser, e.g. Galaxy S8 or S9 

**Expected behavior**
Content is realigned on small screens so that no content is cut off or overlaps the parent container

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/17621496/121406693-becac280-c95e-11eb-892f-d8bb695e8b86.png)

**Desktop**
 - OS: Windows 10
 - Browser: Firefox
 - Version: current

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8
 - OS: Android 9
 - Browser: Firefox
 - Version: current

**Additional context**
Does not depend on selected language

**Comment by MrKrisKrisu** [comment]
fixed in #612
