### ISSUE TITLE
Add Train Type (Baureihe) to Tracking

### ISSUE THREAD

**Issue by bendix-dev** [Traewelling/traewelling#447]
Extra input for the train type / “Baureihe“ used on the trip. Ideally there would be a searchable list you can select from.

Maybe also add an additional comment to the train type so you could add additional information like “(12 tlg.)” or “Tfz Nr. 1234”.

**Comment by MrKrisKrisu** [comment]
We have the idea to give the users  the possibility to store values in Key:Value pairs to the CheckIns in each case publicly or privately. We would wait with the implementation until @HerrLevin has made the migration to vue.js, so that we do not have to maintain duplicate endpoints.

**Comment by alehaa** [comment]
Why just not getting this metadata via API automatically? [marudor.de](https://marudor.de/details/ICE%20801/2022-04-16T13:36:00.000Z?station=8002553) and [regenbogen-ice.de](https://regenbogen-ice.de) can display it, so it seems to be available anywhere …
