### ISSUE TITLE
DS100 abbreviations don't work in lowercase in the station search input field

### ISSUE THREAD

**Issue by pascalwittler** [Traewelling/traewelling#496]
Problem:

When I enter a DS100 abbreviation in uppercase for a station into the search input field, most stations are matched correctly. This does not work when I enter the same input in lowercase. Since a search for full station names works case-insensitive, I would expect that this behaviour would also occur when using a DS100 abbreviation.

Steps to reproduce:

1. Login at https://traewelling.de
2. Click on "Dashboard" in the main navigation
3. Search for "Karlsruhe Hbf" and press enter
4. You will get the next departures at Karlsruhe Hbf
5. Search for "karlsruhe hbf" and press enter
6. You will get the same result
7. Search for "RK" and press enter
8. You will get the same result
9. Search for "rk" and press enter
10. You will get the next departures at Regensburg Hbf

**Comment by MrKrisKrisu** [comment]
We deliberately programmed it that way at the time to avoid conflicts with short place names. I am unsure if we should remove this. However, I don't know any places which could overlap with DS100... (Ulm, Au, ... do not exist)

**Comment by MrKrisKrisu** [comment]
There are some DS100 abbreviations which can cause conflicts, so I wouldn't change this here.
