### ISSUE TITLE
Make all DS100 abbreviations available at the station/departure search

### ISSUE THREAD

**Issue by pascalwittler** [Traewelling/traewelling#497]
Many DS100 abbreviations for smaller stations or local S-Bahn stops don't lead to the departures at the expected station/stop but a search for the same station/stop by its full name does work.

Feature request: Make all official DS100 abbreviations available/work at the station/departure search.

An official list published by DB Netze can be found here:
https://fahrweg.dbnetze.com/fahrweg-de/kunden/betrieb/betriebsstellen-1393360

Steps to reproduce the behaviour which should be improved:

1. Login at https://traewelling.de
2. Click on "Dashboard" in the main navigation
3. Search for "Karlsruhe Albtalbahnhof" and press enter
4. You will get the next departures at Karlsruhe Albtalbahnhof
5. Search for "RKAB" and press enter
6. You will get the next departures at Rheinbach Römerkanal

Some other search keywords I checked:

- RKAB
  expected: Karlsruhe Albtalbahnhof
  got: Rheinbach Römerkanal

- RKMAK
  expected: Karlsruhe Marktplatz Kaiserstraße
  got: R.-Markmann-Str., Boizenburg/ Elbe

- RKSE
  expected: Karlsruhe Europaplatz
  got: Rostock Parkstraße

- RKMW
  expected: Karlsruhe Mühlburg West
  got: R.-Markmann-Str., Boizenburg/ Elbe

- RETT
  expected: Ettlingen Stadt
  got: Retzbach-Zellingen

- RMZN
  expected: Menzingen (Baden)
  got: Alarmzentrum, Hauzenberg

- RWRTL
  expected: Wörth Alte Bahnmeisterei
  got: Pertl, Furth im Wald

**Comment by MrKrisKrisu** [comment]
We currently use DB Rest, which is a wrapper around Deutsche Bahn's HAFAS. 
I will see that I update the data soon and use an alternative source. HAFAS does not seem to know all stations.

Example Request: `https://v5.db.transport.rest/stations/RKAB`

**Comment by MrKrisKrisu** [comment]
I've updated your mentioned DS100 abbreviations in our database, so you can use them now for searching station.
