### ISSUE TITLE
Wrong Distance in ringlines

### ISSUE THREAD

**Issue by HerrLevin** [Traewelling/traewelling#50]
This bug results from #37, #38 and possibly #10.

**Describe the bug**
If travelling in a ringline, the wrong distances are calculated.

**To Reproduce**
See #37 and #10

**Expected behavior**
The correct travelled distance

Calculating the real distances (That does not work yet since len(Polyline-Points) != len(Stopovers) and the polyline points don't know when the train stops there).

**Comment by HerrLevin** [comment]
Is this closed with #210? (@MrKrisKrisu)

**Comment by MrKrisKrisu** [comment]
> Is this closed with #210? (@MrKrisKrisu)

No, this is still occurring.

**Comment by MrKrisKrisu** [comment]
# List of Testcases

## S4 around St. Gallen
![image](https://user-images.githubusercontent.com/4103693/148577277-e5663f8a-1768-41f8-b466-932db0c8e06e.png)

## Line 63 around Langenthal
![image](https://user-images.githubusercontent.com/4103693/148577331-3289f715-84cf-4602-918f-1b705dd7ab15.png)

## Line 52 around Langenthal 
This is not a ringline, but some stops will be approached several times
![image](https://user-images.githubusercontent.com/4103693/148577397-04ef4bfc-7221-4d1d-bea8-bfff581aec64.png)
