### ISSUE TITLE
Misinterpreted train cancellations

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/traewelling#503]
**Describe the bug**
If the departure is cancelled but the arrival is still carried out you cannot check in. We seem to be misinterpreting that.

See Leipzig Hbf (tief) in the following screenshots.

**Screenshots**
<img src="https://user-images.githubusercontent.com/4103693/133081821-5deb6b47-d23e-4202-9ce1-8738128f9a47.png" height="400">
<img src="https://user-images.githubusercontent.com/4103693/133081849-214cb3c8-276f-426f-a94b-7ddc511e5d20.png" height="400">

**Comment by HerrLevin** [comment]
Duplicate #21, see https://github.com/Traewelling/traewelling/issues/21#issuecomment-1057803925
