### ISSUE TITLE
Describe what "Travel Volume" is

### ISSUE THREAD

**Issue by jeyemwey** [Traewelling/traewelling#509]
**Describe the bug**
It is unclear to me, what "Reisevolumen" should describe. It is not the distance (I have traveled more than 1000km in the last week), so what is it?

**To Reproduce**

1. Go to your Stats Page
2. Be confused

**Expected behavior**
There is a hint text or a label on the Y axis describing how "Reisevolumen" is defined.

**Screenshots**
![Screenshot_20210917-133207.png](https://user-images.githubusercontent.com/2796271/133776151-7ff4f580-ed19-4ba5-98ce-b297b650128c.png)

**Comment by MrKrisKrisu** [comment]
I would close this, because i think it is well described by now.

<img width="276" alt="Screen Shot 2022-07-23 at 11 56 16" src="https://user-images.githubusercontent.com/4103693/180600391-b6456a8e-a88a-4c24-8e9d-a23ec8dd4a62.png">
