### ISSUE TITLE
Remove Twitter association if account was deleted

### ISSUE THREAD

**Issue by marvinborner** [Traewelling/traewelling#511]
**Describe the bug**
You can no longer access/reset/delete your account if the associated Twitter account has been deleted. An example is my Träwelling account [@marvinborner](https://traewelling.de/profile/marvinborner) as I can't access the account nor can I reset it using the email address of the deleted Twitter account. You can also see that the Twitter button on my profile redirects to a 404 page of Twitter.

**To Reproduce**
1. Create a Träwelling account using your Twitter account
2. Deactivate/delete your Twitter account
3. Logout from your Träwelling account
4. There's no way to access/reset/delete your Träwelling account

**Possible solutions**
I thought of several solutions for this problem. Firstly, the associated Träwelling account could be deleted/deactivated automatically if this happens (which obviously isn't optimal). Secondly, you could also allow resetting the Träwelling account using the deleted Twitter account email (I don't know if that's technically possible, though).
Maybe you/we could also investigate how other services are solving this problem.

**Comment by jeyemwey** [comment]
> Secondly, you could also allow resetting the Träwelling account using the deleted Twitter account email (I don't know if that's technically possible, though).

At this point, Twitter does not give us the users email (yet). There is a way to get the email address, but this requires manual submission of our app to Twitter and doesn't help with existing API tokens. [See forum thread](https://twittercommunity.com/t/how-to-get-email-from-twitter-api/50858).

> Maybe you/we could also investigate how other services are solving this problem.

I can tell from my experience with Spotify's Facebook login that they require a manual unlinking of the account via their support team. If the fb account is gone, there is no way to get access to the Spotify account again.

**Comment by marvinborner** [comment]
Huh, that's very interesting. Who would I need to contact to manually unlink my account? It would help if there was a support/contact email address linked somewhere. I've already tried contacting the email address provided in the privacy policy (levin@...) a few weeks ago and never got a response.

**Comment by MrKrisKrisu** [comment]
> Twitter does not give us the users email (yet). There is a way to get the email address

I would also prefer to store less data on users. So rather not additionally query the registered Twitter email, in my opinion.

**Comment by jeyemwey** [comment]
> Who would I need to contact to manually unlink my account?

I meant that this is how Spotify does it. We don't have a process for that right now.

> I've already tried contacting the email address provided in the privacy policy (levin@...) a few weeks ago and never got a response.

We are sorry for the delay. Levin has received the email and will come back to you.

**Comment by marvinborner** [comment]
I've got a response and the issue has been resolved. Thanks.

**Comment by MrKrisKrisu** [comment]
I would like to leave this issue open and proceed that way:

We regularly check if the account still exists and delete the assignment if necessary. This way, at least incorrect data is no longer available.

**Comment by MrKrisKrisu** [comment]
I think we can close this issue since trwl removed Twitter Support.
