### ISSUE TITLE
You can Check-In in the same connection multiple times

### ISSUE THREAD

**Issue by SoraCent** [Traewelling/traewelling#514]
**Describe the bug**
If you Checked-In a train/bus/etc you can press the back Button on the Phone or Browser and you can Check-In again.
On the Webseite Träwelling thinks it's an other User and writes "@myusername is in the same connection".

**To Reproduce**

1. Check-In
2. Press Back on the Phone or Browser
3. Click Check-In again
4. See that you checked in twice in the same connection

**Expected behavior**
A Error or Message saying you are already checked-in, in this connection

**Screenshots**

**Desktop:**

- OS: Windows 10
- Browser: tested in Firefox 92 and Chrome 93

**Smartphone:**

- Device: Huawei P20 Pro & Huawei P30 Pro
- OS: Android 10
- Browser Firefox Beta
- Version 93

**Comment by jeyemwey** [comment]
I guess that has to do with the [updated](https://github.com/Traewelling/traewelling/pull/508) „You’re already on a trip“ grace period. Thanks for noticing.

**Comment by MrKrisKrisu** [comment]
> I guess that has to do with the [updated](https://github.com/Traewelling/traewelling/pull/508) „You’re already on a trip“ grace period. Thanks for noticing.

I don't think so. This bug has been around for a while. 

See #231
