### ISSUE TITLE
[APIv1] 1 point for any check-in

### ISSUE THREAD

**Issue by jheubuch** [Traewelling/traewelling#523]
**Describe the bug**
When using APIv1 for any check-in, you'll however only gain one point for that journey.

**To Reproduce**

1. Create a check-in via API v1
2. See response, one point is given to the user

**Expected behavior**
The correct amount of points (using the calculation formula) is given to the user.

**Screenshots**
![image](https://user-images.githubusercontent.com/60344409/135076360-1ab6b900-f881-491c-acf0-a2a098c74b1c.png)

**Comment by MrKrisKrisu** [comment]
The new calculation methods in #484 will fix this issue.
