### ISSUE TITLE
[APIv1] Reformat structure of polyline objects

### ISSUE THREAD

**Issue by jheubuch** [Traewelling/traewelling#574]
When requesting the polylines for a status, at the moment a object is returned, which cannot be interpreted by a type-safe programming language.
![image](https://user-images.githubusercontent.com/60344409/138129361-b2511fdc-979d-4ab3-81e0-a589dfdf9d83.png)

The structure of the object cannot be determined at compile-time because the property-names are dynamically set to the status ID of the requested polyline.
Furthermore the coordinates are stored in an array. Those also could be a special object so that each latitude/longitude can be correctly interpreted.

Suggestion for a object structure:
![image](https://user-images.githubusercontent.com/60344409/138130220-dc2edac5-8d15-4c02-b5ab-e45ca5d7d832.png)

That structure could be interpreted by a type-safe programming language.

**Comment by jheubuch** [comment]
(the coordinates-object could be optional, but I think a restructuring of the "outer object" (polyline) is absolutely appropriate :D )

**Comment by MrKrisKrisu** [comment]
I would rather prefer to use a standardized format. Maybe just a GeoJSON object?

/cc @HerrLevin
