### ISSUE TITLE
API v1 Wrong array type is returned for departures

### ISSUE THREAD

**Issue by Vogeslu** [Traewelling/traewelling#584]
**Describe the bug**
In some cases when i want to fetch the departures for a station the data is an object instead of an array (Example: ``/api/v1/trains/station/8010308/departures?when=2021-10-27T15:52:20.172Z``)

Normal Behavior:

```
{
    "data": [
        {
            "tripId": "1|1819680|1|80|27102021",
            // ...
        }
    ],
    "meta": {
        // ...
    }
}
```

Odd Behavior:

```
{
    "data": {
        "1": {
            "tripId": "1|218226|0|80|27102021",
            // ...
        },
        "0": {
            "tripId": "1|1401662|2|80|27102021",
            // ...
        }
    },
    "meta": {
        // ...
    }
}
```

**To Reproduce**

Open ``/api/v1/trains/station/8010308/departures?when=2021-10-27T15:52:20.172Z``

**Comment by jheubuch** [comment]
This behavior occures, when a canceled train is part of the list.
