### ISSUE TITLE
[APIv1] Multiple check-ins possible

### ISSUE THREAD

**Issue by jheubuch** [Traewelling/traewelling#594]
**Describe the bug**
When using the APIv1 check-in route, it is possible to check into multiple connections at the same time

**To Reproduce**
Send multiple requests to the check-in endpoint, all are approved (Statuscode: 200) and all check-ins are created.

**Expected behavior**
409 conflict, when user is already checked in

**Comment by MrKrisKrisu** [comment]
See #231
