### ISSUE TITLE
Timezones are hard.

### ISSUE THREAD

**Issue by jeyemwey** [Traewelling/traewelling#6]
**Describe the bug**
Träwelling is very `CES*T` focused, Trains in Romania (UTC+2) seem to depart in the past.

What is even happening with connections that go over borders? France-UK, Spain-Portugal?

**To Reproduce**
1. Search for a non-CES*T station
2. Compare the departure times with your request times.

**Expected behavior**
The results depart in the `-5 to +15min` interval that is requested.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/2796271/74869587-86156d00-5358-11ea-87fc-2de95d21e304.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser Firefox 68.2.0esr
 - System Timezone: UTC+1

**Additional context**
> On the other hand try to check in to a train in London: The returned trains seem okay, but when you select your destination all stations are one hour in the future.

[Related Gitlab issue](https://gitlab.com/HerrLevin_/trwl/issues/110)

**Comment by MrKrisKrisu** [comment]
I recommend using Carbon which is a library included in Laravel. Carbon automatically respects time zones if specified.
The HAFAS API returned time with time zones (e.g. "2020-09-28T22:15:00+03:00"), so I see no problem there.

**Comment by MrKrisKrisu** [comment]
I have gone through different time zones. It seems to work now. In the meantime we also parse the time zones. If it still occurs please reopen.
