### ISSUE TITLE
Ring line statuses don't render a map. Neither on prod, nor beta

### ISSUE THREAD

**Issue by HerrLevin** [Traewelling/traewelling#603]
**Describe the bug**
When checked into a ring line, the map won't render correctly since the matching won't work properly.

**To Reproduce**

1. Check into ringline
 
**Screenshots**
Polyline on beta: (prod is just gray)
![image](https://user-images.githubusercontent.com/1267894/140301921-52c443f9-208d-499b-b450-44bf6a61311c.png)

Actual polyline:
![image](https://user-images.githubusercontent.com/1267894/140296204-61153a7e-8cf5-418c-b9fc-d59363572df2.png)

**Possible workaround**
1. After cutting down the polyline, check if the result is emtpy. If empty, generate it from the stopovers.
-or-
2. First matching pattern

**See also**
https://beta.traewelling.de/status/226520

**Comment by MrKrisKrisu** [comment]
Fixed in #806 
![image](https://user-images.githubusercontent.com/4103693/161436116-6cb0a358-df4b-4d5f-891c-966ce20c9564.png)
