### ISSUE TITLE
Add more tweet variants

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/traewelling#661]
**Describe the solution you'd like**
If a user will check into a train which departs (for example) in 1 hour or more we can post on twitter and mastodon "Ich bin BALD ..." instead of "Ich bin GERADE"...

Your opinion? @HerrLevin

**Comment by HerrLevin** [comment]
I'm not entirely sure about that. Seems like many many edge cases to me. Maybe we could adapt the current tweet format so that it's more applicable to all scenarios?
