### ISSUE TITLE
The API should use ISO8601

### ISSUE THREAD

**Issue by HerrLevin** [Traewelling/traewelling#69]
**Is your feature request related to a problem? Please describe.**
The API returns a non-standardized date format for things like `created_at` or `updated_at`. 

**Describe the solution you'd like**
Change non-standardized timestamps to a more common standard like ISO8601 or Unix timestamp.

**Comment by MrKrisKrisu** [comment]
APIv1 is already developed with ISO8601 timestamps. Therefore I think we don't need the issue (anymore), since APIv0 is no longer developed.
