### ISSUE TITLE
API: /auth/login: Provide a custom clientName for the API token list

### ISSUE THREAD

**Issue by derf** [Traewelling/traewelling#71]
**Issue:**
https://traewelling.de/settings lists all API Tokens as belonging to the "Träwelling Personal Access Client" service. When a user has logged into Traewelling via more than one API client, this makes it hard to revoke access to a specific app. It's also unclear which apps have been granted access to the user's Traewelling account.

**Suggestion:**
Add clientName and (perhaps) URL parameters to `/auth/login` and list them in the API Token overview.

**Comment by jheubuch** [comment]
@MrKrisKrisu, I think this issue can be closed in view of applications with OAuth2?
