### ISSUE TITLE
API: /trains/checkin only works after requesting /trains/trip

### ISSUE THREAD

**Issue by derf** [Traewelling/traewelling#72]
**Describe the bug**
Checking into a train using `/trains/checkin` and a valid tripID, start and stop station results in HTTP 500 unless a request to `/trains/trip` is sent first.

**To Reproduce**
```
curl  -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ..." https://traewelling.de/api/v0/trains/checkin --data '{"tripID":...}'
```

-> HTTP 500 "Server Error"

```
curl  -H "Content-Type: application/json" -H "Authorization: Bearer ..." 'https://traewelling.de/api/v0/trains/trip?tripID=...&lineName=...&start=...'
curl  -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ..." https://traewelling.de/api/v0/trains/checkin --data '{"tripID":...}'
```

-> works fine

**Expected behavior**
`/trains/checkin` should work regardless of previous `/trains/trip` requests.

**Comment by jeyemwey** [comment]
This is likely a problem with [`TransportController::getHafasTrip`](https://github.com/Traewelling/traewelling/blob/f21717bb5857b7a370f883a752310400641568b2/app/Http/Controllers/TransportController.php#L439). This function is called both by `/trains/trip` and `/trains/checkin` and requests the train data from the DB API, if it cannot find this train in the database. @HerrLevin, can you help why this is broken?

**Comment by HerrLevin** [comment]
Note to self: A similar behavior might occur with the `TrainTrip`-method while looking for a trainstation. This should also be addressed in future bugfixes.
