### ISSUE TITLE
Server error 500 when opening my profile

### ISSUE THREAD

**Issue by bodems** [Traewelling/traewelling#75]
Whenever I try to open my profile page https://traewelling.de/profile/bodems I get a 500 error from the webserver. Other profiles works and the problem occurs also when I am not logged in and use another browser or device.

**Comment by bodems** [comment]
I still get a 500 when opening my profile

**Comment by HerrLevin** [comment]
That's because I forgot to merge. Sorry.
Am Mo, 27. Jul 2020, um 16:35, schrieb bodems:

**Comment by bodems** [comment]
I saw it and deleted the comment ;)
Thanks for all!
