### ISSUE TITLE
Privacy feature: Set status visibility to private after any period of time

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/traewelling#754]
**Describe the solution you'd like**
A user can set a time period in the settings after which his CheckIns will automatically become private.

**Describe alternatives you've considered**
Manually set everything to private? 🤡

**Comment by o1eeeee** [comment]
Hi, this feature doesn‘t seem to work for me. I set the period to 3 days (now 2 days), but my check-ins before April 11, 2023 are still visible to all registered users instead of being private.
