### ISSUE TITLE
Potsdam is weird

### ISSUE THREAD

**Issue by jeyemwey** [Traewelling/traewelling#794]
**Describe the bug**
When checking into local transport in Potsdam, weird errors occur. 

**To Reproduce**

1. Find a Station in Potsdam, e.g. _Potsdam Plantagenstr._ (IBNR: 736165)
2. Find a tram or bus stop, e.g. _STR 99_
3. Try to checkin later on that trip, e.g. at _S Babelsberg/Wattstr._

**Expected behavior**
Successful checkin with correct distance.

**Additional context**
This happens with the main application, the admin interface, and in some cases with the Android app (however, @jheubuch said that the app does not encode slashes in URIs correctly).  The issue was originally reported by @jeriox in the hotline.

**Comment by jeriox** [comment]
@jeyemwey I tried to reproduce the bug on a local instance, but everything worked flawlessly. I could also check in to the connection from yesterday that produced this bug: https://traewelling.de/status/312606
Do you have any ideas on how to narrow this down?

**Comment by MrKrisKrisu** [comment]
Did you test it before or after the commit from #789 two hours ago?

This PR changed the check-in method to a newer one and also contains an improvement for ring lines.

**Comment by jeriox** [comment]
My local repo was on 841cb7ca4e76a24ec79ae16a110130be249b3b23 while testing.

I just noticed that all checkins that I had trouble with in the last two days that I could now check in to are displayed with a distance of 0km. This applies to the checkin above as well as https://traewelling.de/status/312609 and https://traewelling.de/status/312610

**Comment by MrKrisKrisu** [comment]
That's hard to reproduce. I tried to check into your statuses, but the calculated distance is > 0. 

![image](https://user-images.githubusercontent.com/4103693/161423619-1051cf8b-a672-4c04-a5b6-4a5a17437b3e.png)

**Comment by MrKrisKrisu** [comment]
For this trip the calculated distance is weird. I don't know this line, but based on the polyline displayed, I doubt that the ride is 12 km long.

![image](https://user-images.githubusercontent.com/4103693/161423683-c8a0633a-798c-4b7e-a3d3-9bbfc5bfea7b.png)

**Comment by MrKrisKrisu** [comment]
STR 94 is a ring line.
![image](https://user-images.githubusercontent.com/4103693/161423942-978bd158-bbc9-42bb-98b0-5c53424c3877.png)

**Comment by jeriox** [comment]
Oh, I didn't know that this also counts as a ring line because these are two trips (forward to Schloss Charlottenhof and the return trip to Fontanestraße). Thanks for fixing!
