### ISSUE TITLE
Display delays in the status card

### ISSUE THREAD

**Issue by jeyemwey** [Traewelling/traewelling#8]
**Is your feature request related to a problem? Please describe.**

I'd like to save that my trip was delayed, or even built up a delay during the ride.

**Describe the solution you'd like**

* Show the delays (at the departure and the arrival) in the status card.
* Update the arrival delays (via cron?)
* Find a way to deal with late-checkins

**Describe alternatives you've considered**

* Manual text inputs that I can fill if I care about that stuff.

**Additional context**

* After `scheduled+delay`, Deutsche Bahn won't tell us that this train is delayed. We'd have to check that earlier.
* There is a `delay` field in one of the database tables but god knows what it does (how accurate that information is at what time for which station).
* [Related Gitlab issue](https://gitlab.com/HerrLevin_/trwl/issues/146)

**Comment by MrKrisKrisu** [comment]
Closed in #177
