### ISSUE TITLE
Make exit editable while in train

### ISSUE THREAD

**Issue by alehaa** [Traewelling/traewelling#850]
**Is your feature request related to a problem? Please describe.**
Sometimes plans change, especially when a train is late. Therefore, it can be suitable to exit the train at another station than planned. Currently, this requires deleting the current entry in the profile page and re-enter the same train with another exit selected.

**Describe the solution you'd like**
Instead of deleting, entries should be editable. Points should be calculated accordingly (in the allowed timeframe) and checks for errors (e.g. overlapping journeys) be performed.

**Describe alternatives you've considered**
Afaik there's no other solution (besides deleting) right now.

**Additional context**
The edit dialog should show the same list of train stops as when entering the train.

**Comment by MrKrisKrisu** [comment]
duplicate #427 

Btw: Since yesterday it is possible to force the checkins if they are overlapping with another one.
