### ISSUE TITLE
Can't Create Check In with same Destination as Origin Station

### ISSUE THREAD

**Issue by bendix-dev** [Traewelling/traewelling#885]
On ring lines (for example S41 or S42 in Berlin) you can't select the same station as your destination that you selected as your origin station.

One station where you can try it is Berlin Südkreuz.

It neither works on the website nor in the v1 API. You always get a 500 as the HTTP status code.

**Comment by bendix-dev** [comment]
Steps to reproduce:
- get station board for Berlin Südkreuz
- choose S42
- select Berlin Südkreuz (first occurrence) as destination
- confirm check in

one other idea I had: maybe the problem isn't the same destination as origin but rather the destination being in the list two times

**Comment by MrKrisKrisu** [comment]
<img width="766" alt="Screen Shot 2022-05-20 at 12 14 59" src="https://user-images.githubusercontent.com/4103693/169507148-e5a0e6e2-306b-4836-beaa-b221bc80d2e5.png">

I cannot reproduce this. Can you tell me which journey you choose exacly?

**Comment by bendix-dev** [comment]
Oh well I can't reproduce it on prod either, I think we can close this one, sorry.
