### ISSUE TITLE
Allow check in to delayed trains with overlapping scheduled time

### ISSUE THREAD

**Issue by v0tti** [Traewelling/traewelling#920]
I can’t check in to delayed trains if I already have a check in to a train that runs at the delayed trains scheduled times.

Example:
Check in to RE6 Bochum 21:19 - Düsseldorf 22:05. Continue journey to Aachen with RE1 delayed by 45 minutes at 22:25. Result: “You have an overlapping checkin with connection RE 6”.

Please respect the train delay when checking for overlapping connections (the train was displayed correctly while trying to check in).

**Comment by MrKrisKrisu** [comment]
This feature is already implemented in the beta version of traewelling. You can force your checkin at beta.traewelling.de (username + password required).
