### ISSUE TITLE
API doesn't set CORS header in response

### ISSUE THREAD

**Issue by xanderio** [Traewelling/traewelling#94]
**Describe the bug**
When sending a request to the official traewelling instance at https://traewelling.de/api/. The CORS header `Access-Control-Allow-Origin` isn't set in the response with causes the browser to block the request. This make it impossible to create any kind of third party web app.

**To Reproduce**
1. Send a `OPTION` request to any API endpoint `curl -i https://traewelling.de/api/v0/auth/login -X OPTIONS`
2. See missing `Access-Control-Allow-Origin` header

**Expected behavior**
The `Access-Control-Allow-Origin` being set to `*` for all API endpoints.

**Desktop (please complete the following information):**
 - OS: FreeBSD
 - Browser firefox, curl
 - Version firefox 81, curl 7.72.0

**Comment by MrKrisKrisu** [comment]
Since the API is not intended to build a new frontend on a foreign domain, this is not needed in my opinion.

**Comment by xanderio** [comment]
Maybe this is just a communication problem. What is the use case this API is intended for? 

Without this header no interaction with the Traewelling API is possible from any browser what so ever. 

In case the API is not indented for browser usage. Could you please explain your reasoning?
