### ISSUE TITLE
OpenAPI Definition for APIv1

### ISSUE THREAD

**Issue by NyCodeGHG** [Traewelling/traewelling#952]
**Is your feature request related to a problem? Please describe.**
I could only find an OpenAPI Definition of the API Version 0.

**Describe the solution you'd like**
It would be nice to also have an up-to-date definition of the api version one.

**Additional context**
Maybe a hosted documentation page using [Redocly](https://redocly.com/) or Swagger UI would be also nice to have.

**Comment by MrKrisKrisu** [comment]
APIv1 is currently not intended for public use as we are still designing it. Therefore, we have made a conscious decision not to provide documentation yet.

The endpoints are currently subject to change at any time. So you are welcome to use it, but at your own risk and without documentation yet.

**Comment by NyCodeGHG** [comment]
Oh, ok. I didn't know that it's not stable yet. Thank you :)

**Comment by MrKrisKrisu** [comment]
We will definitely provide documentation when APIv1 is stable. :) But this may take some time.

As said: If short term and unannounced API changes are ok for you, feel free to use APIv1. If you have any questions, feel free to contact us.
