### ISSUE TITLE
Some Dashboard Requests Load Very Long

### ISSUE THREAD

**Issue by bendix-dev** [Traewelling/traewelling#961]
Some /dashboard/ pages in API v1 load very long (around 5 seconds for me) and some load very quick (max 500 ms). My suspicion: looks like the pages that took so long to load have statuses with events while the ones that load quick do not.

https://traewelling.de/api/v1/dashboard

**Comment by HerrLevin** [comment]
once #971 is merged & deployed, the fields `trainDistance` and `trainDuration`will be moved to the endpoint `v1/event/{slug}/details`. ~~To reduce breaking changes, these fields will be set to 0 for now in every model that uses the regular event model (this includes statuses).~~

**Comment by jheubuch** [comment]
Fine by me, not implemented yet in my client
